--神司马懿
local m=70002147
local cm=_G["c"..m]
function cm.initial_effect(c)
	c:EnableCounterPermit(0x1270)
	c:SetCounterLimit(0x1270,20)
	--atk
	local e0=Effect.CreateEffect(c)
	e0:SetType(EFFECT_TYPE_SINGLE)
	e0:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e0:SetCode(EFFECT_IGNORE_BATTLE_TARGET)
	e0:SetRange(LOCATION_MZONE)
	e0:SetValue(1)
	c:RegisterEffect(e0)
	--counter 1
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(m,0))
	e1:SetCategory(CATEGORY_SPECIAL_SUMMON+CATEGORY_RECOVER)
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EVENT_DAMAGE)
	e1:SetOperation(cm.couop)
	c:RegisterEffect(e1)
	--counter 2
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e2:SetCode(EVENT_TO_GRAVE)
	e2:SetRange(LOCATION_MZONE)
	e2:SetOperation(cm.counter)
	c:RegisterEffect(e2)
	local e3=e2:Clone()
	e3:SetCode(EVENT_REMOVE)
	c:RegisterEffect(e3)
	--level up
	local e5=Effect.CreateEffect(c)
	e5:SetDescription(aux.Stringid(m,1))
	e5:SetProperty(EFFECT_FLAG_DELAY+EFFECT_FLAG_CANNOT_INACTIVATE+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_CAN_FORBIDDEN)
	e5:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
	e5:SetRange(LOCATION_MZONE)
	e5:SetCountLimit(1,m+EFFECT_COUNT_CODE_DUEL)
	e5:SetCode(EVENT_PHASE+PHASE_STANDBY)
	e5:SetCondition(cm.lvcon)
	e5:SetOperation(cm.lvop)
	c:RegisterEffect(e5)
	--Activate 1(Draw)
	local e6=Effect.CreateEffect(c)
	e6:SetDescription(aux.Stringid(m,2))
	e6:SetCategory(CATEGORY_TODECK+CATEGORY_DRAW)
	e6:SetType(EFFECT_TYPE_IGNITION)
	e6:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e6:SetRange(LOCATION_MZONE)
	e6:SetCountLimit(1,m)
	e6:SetCondition(cm.con1)
	e6:SetCost(cm.cost)
	e6:SetTarget(cm.tg1)
	e6:SetOperation(cm.op1)
	c:RegisterEffect(e6)
	--Activate 2(Act Limit)
	local e7=Effect.CreateEffect(c)
	e7:SetDescription(aux.Stringid(m,3))
	e7:SetType(EFFECT_TYPE_IGNITION)
	e7:SetRange(LOCATION_MZONE)
	e7:SetCountLimit(1,m+1)
	e7:SetCondition(cm.con1)
	e7:SetCost(cm.cost)
	e7:SetOperation(cm.op2)
	c:RegisterEffect(e7)
	--Activate 3(Turn Skip)
	local e8=Effect.CreateEffect(c)
	e8:SetDescription(aux.Stringid(m,4))
	e8:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O)
	e8:SetRange(LOCATION_MZONE)
	e8:SetCode(EVENT_DAMAGE)
	e8:SetCountLimit(1)
	e8:SetCondition(cm.con1)
	e8:SetCost(cm.cost)
	e8:SetTarget(cm.tg3)
	e8:SetOperation(cm.op3)
	c:RegisterEffect(e8)
	--Activate 4(Draw)
	local e9=Effect.CreateEffect(c)
	e9:SetDescription(aux.Stringid(m,5))
	e9:SetCategory(CATEGORY_DRAW)
	e9:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O)
	e9:SetProperty(EFFECT_FLAG_DELAY+EFFECT_FLAG_PLAYER_TARGET)
	e9:SetRange(LOCATION_MZONE)
	e9:SetCode(EVENT_CHAINING)
	e9:SetCondition(cm.con2)
	e9:SetCost(cm.cost)
	e9:SetTarget(cm.tg4)
	e9:SetOperation(cm.op4)
	c:RegisterEffect(e9)
	--Activate 5(ConfirmDecktop)
	local e10=Effect.CreateEffect(c)
	e10:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O)
	e10:SetRange(LOCATION_MZONE)
	e10:SetCode(EVENT_PREDRAW)
	e10:SetCondition(cm.con3)
	e10:SetCost(cm.cost)
	e10:SetOperation(cm.op5)
	c:RegisterEffect(e10)
	--special summon
	local e11=Effect.CreateEffect(c)
	e11:SetDescription(aux.Stringid(m,7))
	e11:SetCode(EVENT_BATTLE_DESTROYING)
	e11:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_O)
	e11:SetCountLimit(1)
	e11:SetOperation(cm.skipop)
	c:RegisterEffect(e11)
	--atk
	local e12=Effect.CreateEffect(c)
	e12:SetType(EFFECT_TYPE_SINGLE)
	e12:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e12:SetRange(LOCATION_MZONE)
	e12:SetCode(EFFECT_SET_BASE_ATTACK)
	e12:SetValue(cm.atkval)
	c:RegisterEffect(e12)
	local e13=e12:Clone()
	e13:SetCode(EFFECT_SET_BASE_DEFENSE)
	c:RegisterEffect(e13)
end
	function cm.atkval(e,c)
	local lv=c:GetLevel()
	return c:GetCounter(0x1270)*lv*100
end
	function cm.couop(e,tp,eg,ep,ev,re,r,rp)
	e:GetHandler():AddCounter(0x1270,1,true)
	Debug.Message("我还耗得起！")
end
	function cm.cfilter(c)
	return c:IsPreviousLocation(LOCATION_HAND)
end
	function cm.counter(e,tp,eg,ep,ev,re,r,rp)
	local ct=eg:FilterCount(cm.cfilter,nil)
	if ct>0 then
		e:GetHandler():AddCounter(0x1270,ct,true)
		Debug.Message("隐忍以行，厚积而薄发。")
	end
end
	function cm.lvcon(e,tp,eg,ep,ev,re,r,rp)
	return Duel.GetTurnPlayer()==tp and e:GetHandler():GetCounter(0x1270)>=4
end
	function cm.lvop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	--level
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_UPDATE_LEVEL)
	e1:SetTargetRange(LOCATION_MZONE,0)
	e1:SetTarget(aux.TargetBoolFunction(Card.IsCode,70002147))
	e1:SetValue(-1)
	Duel.RegisterEffect(e1,tp)
	Debug.Message("拜印封戒，就在今朝！")
end
	function cm.con1(e,tp,eg,ep,ev,re,r,rp)
	return e:GetHandler():IsLevel(3)
end
	function cm.cost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return e:GetHandler():IsCanRemoveCounter(tp,0x1270,1,REASON_COST) end
	e:GetHandler():RemoveCounter(tp,0x1270,1,REASON_COST)
end
	function cm.tg1(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.IsPlayerCanDraw(tp)
		and Duel.IsExistingMatchingCard(Card.IsAbleToDeck,tp,LOCATION_HAND,0,1,e:GetHandler()) end
	Duel.SetTargetPlayer(tp)
	Duel.SetOperationInfo(0,CATEGORY_TODECK,nil,1,tp,LOCATION_HAND)
end
	function cm.op1(e,tp,eg,ep,ev,re,r,rp)
	local p=Duel.GetChainInfo(0,CHAININFO_TARGET_PLAYER)
	Duel.Hint(HINT_SELECTMSG,p,HINTMSG_TODECK)
	local g=Duel.SelectMatchingCard(p,Card.IsAbleToDeck,p,LOCATION_HAND,0,1,63,nil)
	if g:GetCount()==0 then return end
	Duel.SendtoDeck(g,nil,SEQ_DECKSHUFFLE,REASON_EFFECT)
	Duel.ShuffleDeck(p)
	Duel.BreakEffect()
	Duel.Draw(p,g:GetCount(),REASON_EFFECT)
	Debug.Message("用兵勿要弄险，细节决定成败。")
end
	function cm.op2(e,tp,eg,ep,ev,re,r,rp)
	local e2=Effect.CreateEffect(e:GetHandler())
	e2:SetType(EFFECT_TYPE_FIELD)
	e2:SetCode(EFFECT_CANNOT_ACTIVATE)
	e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e2:SetTargetRange(0,1)
	e2:SetValue(1)
	e2:SetCondition(cm.actcon)
	e2:SetReset(RESET_PHASE+PHASE_END)
	Duel.RegisterEffect(e2,tp)
	Debug.Message("老夫倒要看看，谁敢和司马氏作对？")
end
	function cm.actcon(e)
	local ph=Duel.GetCurrentPhase()
	return ph>=PHASE_BATTLE_START and ph<=PHASE_BATTLE
end
	function cm.tg3(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return not Duel.IsPlayerAffectedByEffect(1-tp,EFFECT_SKIP_TURN) end
end
	function cm.op3(e,tp,eg,ep,ev,re,r,rp)
	local e3=Effect.CreateEffect(e:GetHandler())
	e3:SetType(EFFECT_TYPE_FIELD)
	e3:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e3:SetCode(EFFECT_SKIP_TURN)
	e3:SetTargetRange(0,1)
	e3:SetReset(RESET_PHASE+PHASE_END+RESET_OPPO_TURN)
	e3:SetCondition(cm.skipcon)
	Duel.RegisterEffect(e3,tp)
	Duel.Draw(1-tp,2,REASON_EFFECT)
	Debug.Message("我不想再看到你了。")
end
	function cm.skipop(e,tp,eg,ep,ev,re,r,rp)
	local e4=Effect.CreateEffect(e:GetHandler())
	e4:SetType(EFFECT_TYPE_FIELD)
	e4:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e4:SetCode(EFFECT_SKIP_TURN)
	e4:SetTargetRange(0,1)
	e4:SetReset(RESET_PHASE+PHASE_END+RESET_OPPO_TURN)
	e4:SetCondition(cm.skipcon)
	Duel.RegisterEffect(e4,tp)
	Debug.Message("杀戒一开，难再回头！")
end
	function cm.skipcon(e)
	return Duel.GetTurnPlayer()~=e:GetHandlerPlayer()
end
	function cm.con2(e,tp,eg,ep,ev,re,r,rp)
	return re:IsHasType(EFFECT_TYPE_ACTIVATE)
		and re:IsActiveType(TYPE_SPELL) and e:GetHandler():IsLevel(3)
end
	function cm.tg4(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.IsPlayerCanDraw(tp,1) end
	Duel.SetTargetPlayer(tp)
	Duel.SetTargetParam(1)
	Duel.SetOperationInfo(0,CATEGORY_DRAW,nil,0,tp,1)
end
	function cm.op4(e,tp,eg,ep,ev,re,r,rp)
	local p,d=Duel.GetChainInfo(0,CHAININFO_TARGET_PLAYER,CHAININFO_TARGET_PARAM)
	Duel.Draw(p,d,REASON_EFFECT)
	Debug.Message("你能逃出我的计谋吗？")
end
	function cm.con3(e,tp,eg,ep,ev,re,r,rp)
	return e:GetHandler():IsLevel(3)
end
	function cm.op5(e,tp,eg,ep,ev,re,r,rp)
	local g=Duel.GetDecktopGroup(tp,1)
	Duel.ConfirmCards(tp,g)
	local tc=g:GetFirst()
	local opt=Duel.SelectOption(tp,aux.Stringid(40695128,2),aux.Stringid(40695128,3))
	if opt==1 then
		Duel.MoveSequence(tc,opt)
	end
	if Duel.SelectYesNo(tp,aux.Stringid(m,6)) then
	   local sg=Duel.SelectMatchingCard(tp,Card.IsAbleToDeck,tp,LOCATION_ONFIELD+LOCATION_HAND,0,1,1,nil)
	   Duel.SendtoDeck(sg,tp,SEQ_DECKTOP,REASON_EFFECT)
	end
	Debug.Message("你敢与天斗？")
end