function c10111105.initial_effect(c)
	--to gravee
	local e1=Effect.CreateEffect(c)
	e1:SetCategory(CATEGORY_TODECK)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetTarget(c10111105.tg4)
	e1:SetOperation(c10111105.op4)
	c:RegisterEffect(e1) 
    	--draw
	local e2=Effect.CreateEffect(c)
	e2:SetCategory(CATEGORY_TODECK+CATEGORY_DRAW)
	e2:SetDescription(aux.Stringid(10111105,1))
	e2:SetType(EFFECT_TYPE_IGNITION)
	e2:SetRange(LOCATION_GRAVE)
	e2:SetCountLimit(4,10111105)
	e2:SetTarget(c10111105.tdtg)
	e2:SetOperation(c10111105.tdop)
	c:RegisterEffect(e2)
end
function c10111105.tg4(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return true end
	local token1=Duel.CreateToken(tp,10111106)
	local token2=Duel.CreateToken(tp,10111107)
	local token3=Duel.CreateToken(tp,10111108)
    local token4=Duel.CreateToken(tp,10111109)
	local token5=Duel.CreateToken(tp,10111106)
    local token6=Duel.CreateToken(tp,10111107)
    local token7=Duel.CreateToken(tp,10111108)
    local token8=Duel.CreateToken(tp,10111109)
	local g=Group.CreateGroup()
	g:AddCard(token1)
	g:AddCard(token2)
	g:AddCard(token3)
	g:AddCard(token4)
	g:AddCard(token5)
	g:AddCard(token6)
    g:AddCard(token7)
    g:AddCard(token8)
	g:KeepAlive()
	e:SetLabelObject(g)
end
function c10111105.op4(e,tp,eg,ep,ev,re,r,rp)
	local g=e:GetLabelObject()
	if g and g:GetCount()>0 then
		Duel.SendtoDeck(g,nil,2,REASON_EFFECT)
    end
    local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_CANNOT_TO_HAND)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetTargetRange(1,0)
	e1:SetTarget(aux.TargetBoolFunction(Card.IsLocation,LOCATION_DECK))
	e1:SetReset(RESET_PHASE+PHASE_END)
	Duel.RegisterEffect(e1,tp)
end
function c10111105.tdtg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return e:GetHandler():IsAbleToDeck() and Duel.IsPlayerCanDraw(tp,1) end
	Duel.SetOperationInfo(0,CATEGORY_TODECK,e:GetHandler(),1,0,0)
	Duel.SetOperationInfo(0,CATEGORY_DRAW,nil,0,tp,1)
end
function c10111105.tdop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	if c:IsRelateToEffect(e) and Duel.SendtoDeck(c,nil,SEQ_DECKSHUFFLE,REASON_EFFECT)~=0 and c:IsLocation(LOCATION_DECK) then
		Duel.ShuffleDeck(tp)
		Duel.BreakEffect()
		Duel.Draw(tp,1,REASON_EFFECT)
	end
    local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_CANNOT_TO_HAND)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetTargetRange(1,0)
	e1:SetTarget(aux.TargetBoolFunction(Card.IsLocation,LOCATION_DECK))
	e1:SetReset(RESET_PHASE+PHASE_END)
	Duel.RegisterEffect(e1,tp)
end