-- 运压
function c10200025.initial_effect(c)
    -- Activate
    local e1=Effect.CreateEffect(c)
    e1:SetDescription(aux.Stringid(10200025,0))
    e1:SetCategory(CATEGORY_TOHAND+CATEGORY_SEARCH)
    e1:SetType(EFFECT_TYPE_ACTIVATE)
    e1:SetCode(EVENT_FREE_CHAIN)
    e1:SetOperation(c10200025.activate1)
    c:RegisterEffect(e1)
    -- 骰子
    local e2=Effect.CreateEffect(c)
    e2:SetDescription(aux.Stringid(10200025,1))
    e2:SetCategory(CATEGORY_DICE)
    e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
    e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
    e2:SetRange(LOCATION_FZONE)
    e2:SetCountLimit(1)
    e2:SetCode(EVENT_PHASE+PHASE_STANDBY)
    e2:SetTarget(c10200025.tg2)
    e2:SetOperation(c10200025.op2)
    c:RegisterEffect(e2)
end
function c10200025.filter1(c)
    return c:IsEffectProperty(aux.MonsterEffectPropertyFilter(EFFECT_FLAG_DICE)) and not c:IsCode(10200025) and c:IsAbleToHand()
end
function c10200025.activate1(e,tp,eg,ep,ev,re,r,rp)
    local g=Duel.GetMatchingGroup(c10200025.filter1,tp,LOCATION_DECK,0,nil)
    if g:GetCount()>0 and Duel.SelectYesNo(tp,aux.Stringid(10200025,2)) then
        Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_ATOHAND)
        local sg=g:Select(tp,1,1,nil)
        Duel.SendtoHand(sg,nil,REASON_EFFECT)
        Duel.ConfirmCards(1-tp,sg)
    end
end
function c10200025.tg2(e,tp,eg,ep,ev,re,r,rp,chk)
    if chk==0 then return true end
    Duel.SetOperationInfo(0,CATEGORY_DICE,nil,0,tp,1)
    Duel.Hint(HINT_OPSELECTED,1-tp,e:GetDescription())
end
function c10200025.op2(e,tp,eg,ep,ev,re,r,rp)
    local d1=Duel.TossDice(tp,1)
    if Duel.SelectYesNo(1-tp, aux.Stringid(10200025,9)) then
        local d2=Duel.TossDice(1-tp,1)
        if d1 == d2 then
            local g=Duel.GetMatchingGroup(nil,tp,LOCATION_ONFIELD,0,nil)
            if g:GetCount()>0 then
                Duel.SendtoDeck(g,nil,2,REASON_EFFECT)
            end
        else
            if d1==1 then
                local e1=Effect.CreateEffect(e:GetHandler())
                e1:SetType(EFFECT_TYPE_FIELD)
                e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
                e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
                e1:SetTargetRange(1,1)
                e1:SetTarget(c10200025.splimit1)
                e1:SetReset(RESET_PHASE+PHASE_END)
                Duel.RegisterEffect(e1,tp)
                e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,3))
            elseif d1==2 then
                local e1=Effect.CreateEffect(e:GetHandler())
                e1:SetType(EFFECT_TYPE_FIELD)
                e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
                e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
                e1:SetTargetRange(1,1)
                e1:SetTarget(c10200025.splimit2)
                e1:SetReset(RESET_PHASE+PHASE_END)
                Duel.RegisterEffect(e1,tp)
                e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,4))
            elseif d1==3 then
                local e1=Effect.CreateEffect(e:GetHandler())
                e1:SetType(EFFECT_TYPE_FIELD)
                e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
                e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
                e1:SetTargetRange(1,1)
                e1:SetTarget(c10200025.splimit3)
                e1:SetReset(RESET_PHASE+PHASE_END)
                Duel.RegisterEffect(e1,tp)
                e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,5))
            elseif d1==4 then
                local e1=Effect.CreateEffect(e:GetHandler())
                e1:SetType(EFFECT_TYPE_FIELD)
                e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
                e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
                e1:SetTargetRange(1,1)
                e1:SetTarget(c10200025.splimit4)
                e1:SetReset(RESET_PHASE+PHASE_END)
                Duel.RegisterEffect(e1,tp)
                e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,6))
            elseif d1==5 then
                local e1=Effect.CreateEffect(e:GetHandler())
                e1:SetType(EFFECT_TYPE_FIELD)
                e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
                e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
                e1:SetTargetRange(1,1)
                e1:SetTarget(c10200025.splimit5)
                e1:SetReset(RESET_PHASE+PHASE_END)
                Duel.RegisterEffect(e1,tp)
                e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,7))
            elseif d1==6 then
                local e1=Effect.CreateEffect(e:GetHandler())
                e1:SetType(EFFECT_TYPE_FIELD)
                e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
                e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
                e1:SetTargetRange(1,1)
                e1:SetTarget(c10200025.splimit6)
                e1:SetReset(RESET_PHASE+PHASE_END)
                Duel.RegisterEffect(e1,tp)
                e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,8))
            end
            if d2==1 then
                local e2=Effect.CreateEffect(e:GetHandler())
                e2:SetType(EFFECT_TYPE_FIELD)
                e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
                e2:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
                e2:SetTargetRange(1-tp,1-tp)
                e2:SetTarget(c10200025.splimit1)
                e2:SetReset(RESET_PHASE+PHASE_END)
                Duel.RegisterEffect(e2,tp)
                e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,3))
            elseif d2==2 then
                local e2=Effect.CreateEffect(e:GetHandler())
                e2:SetType(EFFECT_TYPE_FIELD)
                e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
                e2:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
                e2:SetTargetRange(1-tp,1-tp)
                e2:SetTarget(c10200025.splimit2)
                e2:SetReset(RESET_PHASE+PHASE_END)
                Duel.RegisterEffect(e2,tp)
                e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,4))
            elseif d2==3 then
                local e2=Effect.CreateEffect(e:GetHandler())
                e2:SetType(EFFECT_TYPE_FIELD)
                e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
                e2:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
                e2:SetTargetRange(1-tp,1-tp)
                e2:SetTarget(c10200025.splimit3)
                e2:SetReset(RESET_PHASE+PHASE_END)
                Duel.RegisterEffect(e2,tp)
                e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,5))
            elseif d2==4 then
                local e2=Effect.CreateEffect(e:GetHandler())
                e2:SetType(EFFECT_TYPE_FIELD)
                e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
                e2:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
                e2:SetTargetRange(1-tp,1-tp)
                e2:SetTarget(c10200025.splimit4)
                e2:SetReset(RESET_PHASE+PHASE_END)
                Duel.RegisterEffect(e2,tp)
                e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,6))
            elseif d2==5 then
                local e2=Effect.CreateEffect(e:GetHandler())
                e2:SetType(EFFECT_TYPE_FIELD)
                e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
                e2:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
                e2:SetTargetRange(1-tp,1-tp)
                e2:SetTarget(c10200025.splimit5)
                e2:SetReset(RESET_PHASE+PHASE_END)
                Duel.RegisterEffect(e2,tp)
                e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,7))
            elseif d2==6 then
                local e2=Effect.CreateEffect(e:GetHandler())
                e2:SetType(EFFECT_TYPE_FIELD)
                e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
                e2:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
                e2:SetTargetRange(1-tp,1-tp)
                e2:SetTarget(c10200025.splimit6)
                e2:SetReset(RESET_PHASE+PHASE_END)
                Duel.RegisterEffect(e2,tp)
            e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,8))
            end
        end
    else
        if d1==1 then
            local e1=Effect.CreateEffect(e:GetHandler())
            e1:SetType(EFFECT_TYPE_FIELD)
            e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
            e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
            e1:SetTargetRange(1,1)
            e1:SetTarget(c10200025.splimit1)
            e1:SetReset(RESET_PHASE+PHASE_END)
            Duel.RegisterEffect(e1,tp)
            e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,3))
        elseif d1==2 then
            local e1=Effect.CreateEffect(e:GetHandler())
            e1:SetType(EFFECT_TYPE_FIELD)
            e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
            e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
            e1:SetTargetRange(1,1)
            e1:SetTarget(c10200025.splimit2)
            e1:SetReset(RESET_PHASE+PHASE_END)
            Duel.RegisterEffect(e1,tp)
            e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,4))
       elseif d1==3 then
            local e1=Effect.CreateEffect(e:GetHandler())
            e1:SetType(EFFECT_TYPE_FIELD)
            e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
            e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
            e1:SetTargetRange(1,1)
            e1:SetTarget(c10200025.splimit3)
            e1:SetReset(RESET_PHASE+PHASE_END)
            Duel.RegisterEffect(e1,tp)
            e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,5))
        elseif d1==4 then
            local e1=Effect.CreateEffect(e:GetHandler())
            e1:SetType(EFFECT_TYPE_FIELD)
            e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
            e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
            e1:SetTargetRange(1,1)
            e1:SetTarget(c10200025.splimit4)
            e1:SetReset(RESET_PHASE+PHASE_END)
            Duel.RegisterEffect(e1,tp)
            e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,6))
        elseif d1==5 then
            local e1=Effect.CreateEffect(e:GetHandler())
            e1:SetType(EFFECT_TYPE_FIELD)
            e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
            e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
            e1:SetTargetRange(1,1)
            e1:SetTarget(c10200025.splimit5)
            e1:SetReset(RESET_PHASE+PHASE_END)
            Duel.RegisterEffect(e1,tp)
            e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,7))
        elseif d1==6 then
            local e1=Effect.CreateEffect(e:GetHandler())
            e1:SetType(EFFECT_TYPE_FIELD)
            e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET + EFFECT_FLAG_CLIENT_HINT)
            e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
            e1:SetTargetRange(1,1)
            e1:SetTarget(c10200025.splimit6)
            e1:SetReset(RESET_PHASE+PHASE_END)
            Duel.RegisterEffect(e1,tp)
            e:GetHandler():RegisterFlagEffect(0, RESET_PHASE+PHASE_END, EFFECT_FLAG_CLIENT_HINT, 1, 0, aux.Stringid(10200025,8))
        end
    end
end
function c10200025.splimit1(e,c)
    return c:IsType(TYPE_FUSION)
end
function c10200025.splimit2(e,c)
    return c:IsType(TYPE_RITUAL)
end
function c10200025.splimit3(e,c)
    return c:IsType(TYPE_SYNCHRO)
end
function c10200025.splimit4(e,c)
    return c:IsType(TYPE_XYZ)
end
function c10200025.splimit5(e,c)
    return c:IsType(TYPE_PENDULUM)
end
function c10200025.splimit6(e,c)
    return c:IsType(TYPE_LINK)
end