--拉克希尔仪式
function c11579802.initial_effect(c)
	--Activate
	local e1=Effect.CreateEffect(c) 
	e1:SetType(EFFECT_TYPE_ACTIVATE) 
	e1:SetCode(EVENT_FREE_CHAIN) 
	e1:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e1:SetTarget(c11579802.actg) 
	e1:SetOperation(c11579802.acop) 
	c:RegisterEffect(e1) 
end
function c11579802.actg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.IsExistingTarget(Card.IsFaceup,tp,LOCATION_MZONE,0,1,nil) and Duel.IsExistingTarget(Card.IsFaceup,tp,0,LOCATION_MZONE,1,nil) end 
	local g1=Duel.SelectTarget(tp,Card.IsFaceup,tp,LOCATION_MZONE,0,1,1,nil)
	local g2=Duel.SelectTarget(tp,Card.IsFaceup,tp,0,LOCATION_MZONE,1,1,nil)
end 
function c11579802.acop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler() 
	local g=Duel.GetChainInfo(0,CHAININFO_TARGET_CARDS):Filter(Card.IsRelateToEffect,nil,e)
	if g:GetCount()==2 then 
		local tc=g:GetFirst() 
		while tc do 
		Duel.NegateRelatedChain(tc,RESET_TURN_SET)
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e1:SetCode(EFFECT_DISABLE)
		g:KeepAlive()
		e1:SetLabelObject(g)
		e1:SetCondition(c11579802.xxcon)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD)
		tc:RegisterEffect(e1)
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e2:SetCode(EFFECT_DISABLE_EFFECT)
		e2:SetValue(RESET_TURN_SET)
		g:KeepAlive()
		e2:SetLabelObject(g)
		e2:SetCondition(c11579802.xxcon)
		e2:SetReset(RESET_EVENT+RESETS_STANDARD) 
		tc:RegisterEffect(e2)
		local e1=Effect.CreateEffect(c)
		e1:SetDescription(aux.Stringid(11579802,1)) 
		e1:SetType(EFFECT_TYPE_SINGLE) 
		e1:SetCode(EFFECT_IMMUNE_EFFECT) 
		e1:SetProperty(EFFECT_FLAG_CLIENT_HINT)
		e1:SetRange(LOCATION_MZONE) 
		e1:SetValue(function(e,te) 
		return e:GetOwner()~=te:GetOwner() end)  
		g:KeepAlive()
		e1:SetLabelObject(g)
		e1:SetCondition(c11579802.xxcon)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD) 
		tc:RegisterEffect(e1) 
		local e1=Effect.CreateEffect(c) 
		e1:SetType(EFFECT_TYPE_SINGLE) 
		e1:SetCode(EFFECT_INDESTRUCTABLE_BATTLE) 
		e1:SetRange(LOCATION_MZONE) 
		g:KeepAlive()
		e1:SetLabelObject(g)
		e1:SetValue(function(e,c) 
		local g=e:GetLabelObject()
		return not g:IsContains(c) end) 
		e1:SetCondition(c11579802.xxcon)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD) 
		tc:RegisterEffect(e1) 
		local e1=Effect.CreateEffect(c) 
		e1:SetType(EFFECT_TYPE_SINGLE) 
		e1:SetCode(EFFECT_SET_ATTACK) 
		e1:SetRange(LOCATION_MZONE) 
		e1:SetValue(function(e) 
		local tp=e:GetHandlerPlayer() 
		local g=Duel.GetMatchingGroup(Card.IsFaceup,tp,LOCATION_MZONE,0,nil)
		return g:GetSum(Card.GetBaseAttack) end) 
		g:KeepAlive()
		e1:SetLabelObject(g)
		e1:SetCondition(c11579802.xxcon) 
		tc:RegisterEffect(e1) 
		local e1=Effect.CreateEffect(c) 
		e1:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS) 
		e1:SetCode(EVENT_LEAVE_FIELD) 
		g:KeepAlive()
		e1:SetLabelObject(g)
		e1:SetOperation(c11579802.lfop) 
		tc:RegisterEffect(e1) 
		tc:RegisterFlagEffect(11579802,RESET_EVENT+RESETS_STANDARD,0,1)
		tc=g:GetNext() 
		end 
	end 
end 
function c11579802.xxcon(e,tp,eg,ep,ev,re,r,rp)
	local g=e:GetLabelObject()
	return g:FilterCount(function(c) return c:GetFlagEffect(11579802)~=0 end,nil)==g:GetCount() 
end 
function c11579802.lfop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler() 
	local g=e:GetLabelObject() 
	local tc=g:Filter(aux.TRUE,c):GetFirst() 
	if tc and tc:IsOnField() then 
		Duel.Hint(HINT_CARD,0,11579802) 
		Duel.Hint(HINT_MESSAGE,0,aux.Stringid(11579802,0))
		Duel.Hint(HINT_MESSAGE,1,aux.Stringid(11579802,0))
		local e1=Effect.CreateEffect(tc) 
		e1:SetDescription(aux.Stringid(11579802,2))
		e1:SetType(EFFECT_TYPE_SINGLE) 
		e1:SetCode(EFFECT_IMMUNE_EFFECT) 
		e1:SetProperty(EFFECT_FLAG_CLIENT_HINT)
		e1:SetRange(LOCATION_MZONE) 
		e1:SetValue(function(e,te) 
		return e:GetOwner()~=te:GetOwner() end)   
		e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END) 
		tc:RegisterEffect(e1,true) 
		local e1=Effect.CreateEffect(tc)  
		e1:SetType(EFFECT_TYPE_SINGLE) 
		e1:SetCode(EFFECT_UPDATE_ATTACK)  
		e1:SetRange(LOCATION_MZONE) 
		e1:SetValue(c:GetAttack())   
		e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END) 
		tc:RegisterEffect(e1)  
	end 
end  







