--拉之天秤
local s,id,o=GetID()
function s.initial_effect(c)
    --cannot special summon
	local e0=Effect.CreateEffect(c)
	e0:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e0:SetType(EFFECT_TYPE_SINGLE)
	e0:SetCode(EFFECT_SPSUMMON_CONDITION)
	c:RegisterEffect(e0)
    --battle
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_INDESTRUCTABLE_BATTLE)
    e1:SetCondition(function(e)
	    return Duel.GetLP(0)==Duel.GetLP(1) end)
	e1:SetValue(1)
	c:RegisterEffect(e1)
    --immune
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetCode(EFFECT_IMMUNE_EFFECT)
	e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e2:SetRange(LOCATION_MZONE)
    e2:SetCondition(function(e)
	    return Duel.GetLP(0)==Duel.GetLP(1) end)
	e2:SetValue(s.efilter)
	c:RegisterEffect(e2)
    --Immune Damage
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD)
	e3:SetRange(LOCATION_MZONE)
	e3:SetCode(EFFECT_CHANGE_DAMAGE)
	e3:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e3:SetTargetRange(1,0)
	e3:SetCondition(s.damcon1)
	e3:SetValue(0)
	c:RegisterEffect(e3)
	local e4=e3:Clone()
	e4:SetCode(EFFECT_NO_EFFECT_DAMAGE)
	c:RegisterEffect(e4)
	local e5=e3:Clone()
	e5:SetTargetRange(0,1)
	e5:SetCondition(s.damcon2)
	c:RegisterEffect(e5)
	local e6=e5:Clone()
	e6:SetCode(EFFECT_NO_EFFECT_DAMAGE)
	c:RegisterEffect(e6)
    --damage reduce
	local e7=Effect.CreateEffect(c)
	e7:SetType(EFFECT_TYPE_FIELD)
	e7:SetCode(EFFECT_CHANGE_DAMAGE)
	e7:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e7:SetRange(LOCATION_MZONE)
	e7:SetTargetRange(1,1)
    e7:SetCondition(function(e)
	    return Duel.GetLP(0)==Duel.GetLP(1) end)
	e7:SetValue(s.damva1)
	c:RegisterEffect(e7)
	local e8=e7:Clone()
	e8:SetCode(EFFECT_NO_EFFECT_DAMAGE)
	c:RegisterEffect(e8)
    local e9=Effect.CreateEffect(c)
    e9:SetType(EFFECT_TYPE_FIELD)
    e9:SetCode(EFFECT_CHANGE_DAMAGE)
    e9:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
    e9:SetRange(LOCATION_MZONE)
    e9:SetCondition(function(e)
        local tp=e:GetHandlerPlayer()
	    return Duel.GetLP(tp)>Duel.GetLP(1-tp) end)
    e9:SetTargetRange(1,0)
    e9:SetValue(s.damva2)
    c:RegisterEffect(e9)
    local e10=e9:Clone()
    e10:SetCondition(function(e)
        local tp=e:GetHandlerPlayer()
	    return Duel.GetLP(tp)<Duel.GetLP(1-tp) end)
    e10:SetTargetRange(0,1)
    c:RegisterEffect(e10)
    --cannot material
	local e11=Effect.CreateEffect(c)
	e11:SetType(EFFECT_TYPE_SINGLE)
	e11:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e11:SetCode(EFFECT_CANNOT_BE_FUSION_MATERIAL)
	e11:SetValue(function(e,c,sumtype)
	    return sumtype==SUMMON_TYPE_FUSION end)
	c:RegisterEffect(e11)
	local e12=e11:Clone()
	e12:SetCode(EFFECT_CANNOT_BE_SYNCHRO_MATERIAL)
	e12:SetValue(1)
	c:RegisterEffect(e12)
	local e13=e12:Clone()
	e13:SetCode(EFFECT_CANNOT_BE_XYZ_MATERIAL)
	c:RegisterEffect(e13)
	local e14=e12:Clone()
	e14:SetCode(EFFECT_CANNOT_BE_LINK_MATERIAL)
	c:RegisterEffect(e14)
    --Damage(100)
	local e15=Effect.CreateEffect(c)
	e15:SetDescription(aux.Stringid(id,0))
	e15:SetCategory(CATEGORY_DAMAGE)
	e15:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
	e15:SetCode(EVENT_PHASE+PHASE_END)
	e15:SetCountLimit(1)
	e15:SetRange(LOCATION_MZONE)
    e15:SetTarget(s.damtg)
	e15:SetOperation(s.damop)
	c:RegisterEffect(e15)
end
function s.efilter(e,te)
	return te:GetOwner()~=e:GetOwner()
end
function s.damcon1(e)
	local tp=e:GetHandlerPlayer()
	return Duel.GetLP(tp)<Duel.GetLP(1-tp)
end
function s.damcon2(e)
	local tp=e:GetHandlerPlayer()
	return Duel.GetLP(1-tp)<Duel.GetLP(tp)
end
function s.damva1(e,re,val,r,rp,rc)
	if bit.band(r,REASON_EFFECT)~=0 and Duel.GetLP(0)==Duel.GetLP(1) then
        return 0
    end
	return val
end
function s.damva2(e,re,val,r,rp,rc)
    local tp=e:GetHandlerPlayer()
    local Lp1=Duel.GetLP(tp)
    local Lp2=Duel.GetLP(1-tp)
    if Lp1~=Lp2 and val>0 then
       if Lp1>Lp2 then val=Lp1-Lp2
       else val=Lp2-Lp1 end
    end
	return math.floor(val)
end
function s.damtg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return true end
	Duel.SetTargetParam(100)
	Duel.SetOperationInfo(0,CATEGORY_DAMAGE,nil,0,PLAYER_ALL,100)
end
function s.damop(e,tp,eg,ep,ev,re,r,rp)
	Duel.Damage(tp,100,0x40)
    Duel.Damage(1-tp,100,0x40)
end