--外舞斗-双骑的协奏曲
local s,id,o=GetID()
function s.initial_effect(c)
	aux.AddCodeList(c,12823280)
	--Activate
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetOperation(s.activate)
	c:RegisterEffect(e1)
end
function s.activate(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local cl=Duel.GetCurrentChain()
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(id,1))
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_CLIENT_HINT)
	e1:SetReset(RESET_PHASE+PHASE_END)
	e1:SetTargetRange(1,0)
	Duel.RegisterEffect(e1,tp)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD)
	e3:SetCode(EFFECT_HAND_LIMIT)
	e3:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e3:SetRange(LOCATION_HAND)
	e3:SetCondition(s.pcon)
	e3:SetTargetRange(1,0)
	e3:Reset(RESET_PHASE+PHASE_END)
	e3:SetValue(100)
	c:RegisterEffect(e3)
	if cl==4 and Duel.SelectYesNo(tp,aux.Stringid(id,3)) then
		Duel.BreakEffect()
		Duel.Hint(HINT_MUSIC,0,aux.Stringid(id,2))
		--activate from hand
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_FIELD)
		e2:SetCode(EFFECT_QP_ACT_IN_NTPHAND)
		e2:SetTargetRange(LOCATION_HAND,0)
		e2:SetTarget(aux.TargetBoolFunction(Card.IsSetCard,0xca70))
		e2:SetReset(RESET_PHASE+PHASE_END,2)
		Duel.RegisterEffect(e2,tp)
		local e4=Effect.CreateEffect(c)
		e4:SetDescription(aux.Stringid(id,0))
		e4:SetType(EFFECT_TYPE_FIELD)
		e4:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_CLIENT_HINT)
		e4:SetReset(RESET_PHASE+PHASE_END,2)
		e4:SetTargetRange(1,0)
		Duel.RegisterEffect(e4,tp)
	end
end
function s.pcon(e,tp,eg,ep,ev,re,r,rp)
	local tp=e:GetHandlerPlayer()
	return Duel.IsExistingMatchingCard(s.pfilter,tp,LOCATION_ONFIELD,0,1,nil)
end
function s.pfilter(c)
	return c:IsCode(12823280) and c:IsFaceup()
end
