--无形重压 星械圣光
local m=14000703
local cm=_G["c"..m]
function cm.initial_effect(c)
	c:EnableReviveLimit()
	--limit
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(m,0))
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_NO_TURN_RESET+EFFECT_FLAG_INITIAL)
	e1:SetCode(EVENT_PREDRAW)
	e1:SetRange(0xff)
	e1:SetCountLimit(1,m+EFFECT_COUNT_CODE_DUEL)
	e1:SetCondition(cm.con)
	e1:SetOperation(cm.op)
	c:RegisterEffect(e1)
	--summon success
	local e2=Effect.CreateEffect(c)
	e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_NO_TURN_RESET+EFFECT_FLAG_INITIAL)
	e2:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e2:SetCode(EVENT_SUMMON_SUCCESS)
	e2:SetOperation(cm.sumsuc)
	c:RegisterEffect(e2)
end
function cm.con(e,c)
	return not e:GetHandler():IsPublic()
end
function cm.op(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	Duel.ConfirmCards(1-tp,c)
	if not c:IsLocation(LOCATION_HAND) then
		Duel.ConfirmCards(tp,e:GetHandler())
	end
	Duel.Hint(HINT_OPSELECTED,1-tp,aux.Stringid(m,1))
	Duel.Hint(HINT_OPSELECTED,tp,aux.Stringid(m,1))
	--act limit
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetTargetRange(0,1)
	e1:SetCondition(cm.aclcon)
	Duel.RegisterEffect(e1,tp)
	local e2=e1:Clone()
	e2:SetTargetRange(1,0)
	e2:SetCondition(cm.aclcon1)
	Duel.RegisterEffect(e2,tp)
	local e3=e1:Clone()
	e3:SetCode(EFFECT_CANNOT_FLIP_SUMMON)
	Duel.RegisterEffect(e3,tp)
	local e4=e2:Clone()
	e4:SetCode(EFFECT_CANNOT_FLIP_SUMMON)
	Duel.RegisterEffect(e4,tp)
	local e5=e1:Clone()
	e5:SetCode(EFFECT_CANNOT_SUMMON)
	Duel.RegisterEffect(e5,tp)
	local e6=e2:Clone()
	e6:SetCode(EFFECT_CANNOT_SUMMON)
	Duel.RegisterEffect(e6,tp)
	local e7=e1:Clone()
	e7:SetCode(EFFECT_CANNOT_MSET)
	Duel.RegisterEffect(e7,tp)
	local e8=e2:Clone()
	e8:SetCode(EFFECT_CANNOT_MSET)
	Duel.RegisterEffect(e8,tp)
	local e9=e1:Clone()
	e9:SetCode(EFFECT_CANNOT_SSET)
	Duel.RegisterEffect(e9,tp)
	local e10=e2:Clone()
	e10:SetCode(EFFECT_CANNOT_SSET)
	Duel.RegisterEffect(e10,tp)
end
function cm.aclcon(e,c)
	local p=e:GetHandlerPlayer()
	return Duel.GetFlagEffect(p,m)==0 and not Duel.IsPlayerAffectedByEffect(1-p,14000705)
end
function cm.aclcon1(e,c)
	local p=e:GetHandlerPlayer()
	return Duel.GetFlagEffect(p,m)==0 and Duel.IsPlayerAffectedByEffect(1-p,14000705)
end
function cm.sumsuc(e,tp,eg,ep,ev,re,r,rp)
	Duel.RegisterFlagEffect(tp,m,0,0,0)
end