--破碎之神
local m=21099999
local cm=_G["c"..m]
function cm.initial_effect(c)
	c:EnableReviveLimit()
	--limit
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(m,0))
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_NO_TURN_RESET+EFFECT_FLAG_INITIAL)
	e1:SetCode(EVENT_PREDRAW)
	e1:SetRange(0xff)
	e1:SetCountLimit(1,m+EFFECT_COUNT_CODE_DUEL)
	e1:SetCondition(cm.con)
	e1:SetOperation(cm.op)
	c:RegisterEffect(e1)
	--summon success
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e2:SetCode(EVENT_SUMMON_SUCCESS)
	e2:SetOperation(cm.sumsuc)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_NO_TURN_RESET+EFFECT_FLAG_INITIAL)
	e3:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e3:SetCode(EVENT_SUMMON_SUCCESS)
	e3:SetOperation(cm.sumsuc)
	c:RegisterEffect(e3)
	local e4=Effect.CreateEffect(c)
	e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_NO_TURN_RESET+EFFECT_FLAG_INITIAL)
	e4:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e4:SetCode(EVENT_SUMMON_SUCCESS)
	e4:SetOperation(cm.sumsuc)
	c:RegisterEffect(e4)
	
	
end
function cm.con(e,c)
	return not e:GetHandler():IsPublic()
end
function cm.op(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	Duel.ConfirmCards(1-tp,c)
	if not c:IsLocation(LOCATION_HAND) then
		Duel.ConfirmCards(tp,e:GetHandler())
	end
	Duel.Hint(HINT_OPSELECTED,1-tp,aux.Stringid(m,1))
	Duel.Hint(HINT_OPSELECTED,tp,aux.Stringid(m,1))
	--act limit
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_CANNOT_ACTIVATE)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetTargetRange(0,1)
	e1:SetCondition(cm.aclcon)
	e1:SetValue(cm.aclimit)
	Duel.RegisterEffect(e1,tp)
	--act limit
	local e11=Effect.CreateEffect(c)
	e11:SetType(EFFECT_TYPE_FIELD)
	e11:SetTargetRange(0,0xff)
	e11:SetCondition(cm.aclcon2)
	e11:SetTarget(cm.disable)
	e11:SetCode(EFFECT_DISABLE)
	Duel.RegisterEffect(e11,tp)
	local e21=e11:Clone()
	e21:SetTargetRange(0xff,0)
	e21:SetCondition(cm.aclcon1)
	Duel.RegisterEffect(e21,tp)
	local e31=e11:Clone()
	e31:SetTarget(cm.disable)
	e31:SetCode(EFFECT_DISABLE_EFFECT)
	Duel.RegisterEffect(e31,tp)
	local e41=e21:Clone()
	e41:SetTargetRange(0xff,0)
	e41:SetCondition(cm.aclcon1)
	Duel.RegisterEffect(e41,tp)
	local e51=Effect.CreateEffect(c)
	e51:SetType(EFFECT_TYPE_CONTINUOUS+EFFECT_TYPE_FIELD)
	e51:SetCode(EVENT_CHAIN_SOLVING)
	e51:SetCondition(cm.discon)
	e51:SetOperation(cm.disop)
	Duel.RegisterEffect(e51,tp)
	local e61=e51:Clone()
	e61:SetCondition(cm.discon1)
	Duel.RegisterEffect(e61,tp)
	local e12=Effect.CreateEffect(c)
	e12:SetType(EFFECT_TYPE_FIELD)
	e12:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
	e12:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e12:SetTargetRange(0,1)
	e12:SetCondition(cm.aclcon3)
	Duel.RegisterEffect(e12,tp)
	local e22=e12:Clone()
	e22:SetTargetRange(1,0)
	e22:SetCondition(cm.aclcon12)
	Duel.RegisterEffect(e22,tp)
	local e32=e12:Clone()
	e32:SetCode(EFFECT_CANNOT_FLIP_SUMMON)
	Duel.RegisterEffect(e32,tp)
	local e42=e22:Clone()
	e42:SetCode(EFFECT_CANNOT_FLIP_SUMMON)
	Duel.RegisterEffect(e42,tp)
	local e52=e12:Clone()
	e52:SetCode(EFFECT_CANNOT_SUMMON)
	Duel.RegisterEffect(e52,tp)
	local e62=e22:Clone()
	e62:SetCode(EFFECT_CANNOT_SUMMON)
	Duel.RegisterEffect(e62,tp)
	local e72=e12:Clone()
	e72:SetCode(EFFECT_CANNOT_MSET)
	Duel.RegisterEffect(e72,tp)
	local e82=e22:Clone()
	e82:SetCode(EFFECT_CANNOT_MSET)
	Duel.RegisterEffect(e82,tp)
	local e92=e12:Clone()
	e92:SetCode(EFFECT_CANNOT_SSET)
	Duel.RegisterEffect(e92,tp)
	local e102=e22:Clone()
	e102:SetCode(EFFECT_CANNOT_SSET)
	Duel.RegisterEffect(e102,tp)
end
function cm.aclcon(e,c)
	return Duel.GetFlagEffect(e:GetHandlerPlayer(),m)==0
end
function cm.aclimit(e,re,tp)
	return true
end
function cm.aclcon2(e,c)
	local p=e:GetHandlerPlayer()
	return Duel.GetFlagEffect(p,m)==0 and not Duel.IsPlayerAffectedByEffect(1-p,14000705)
end
function cm.aclcon1(e,c)
	local p=e:GetHandlerPlayer()
	return Duel.GetFlagEffect(p,m)==0 and Duel.IsPlayerAffectedByEffect(1-p,14000705)
end
function cm.disable(e,c)
	return (c:IsType(TYPE_EFFECT) or bit.band(c:GetOriginalType(),TYPE_EFFECT)==TYPE_EFFECT) or not c:IsType(TYPE_MONSTER) and not (c:IsFacedown() and c:IsLocation(LOCATION_EXTRA))
end
function cm.discon(e,tp,eg,ep,ev,re,r,rp)
	local tp=e:GetHandlerPlayer()
	return re:GetHandler():IsControler(1-tp) and Duel.GetFlagEffect(tp,m)==0 and not Duel.IsPlayerAffectedByEffect(1-tp,14000705)
end
function cm.discon1(e,tp,eg,ep,ev,re,r,rp)
	local tp=e:GetHandlerPlayer()
	return re:GetHandler():IsControler(1-tp) and Duel.GetFlagEffect(tp,m)==0 and Duel.IsPlayerAffectedByEffect(1-tp,14000705)
end
function cm.disop(e,tp,eg,ep,ev,re,r,rp)
	Duel.NegateEffect(ev)
end

function cm.aclcon3(e,c)
	local p=e:GetHandlerPlayer()
	return Duel.GetFlagEffect(p,m)==0 and not Duel.IsPlayerAffectedByEffect(1-p,14000705)
end
function cm.aclcon12(e,c)
	local p=e:GetHandlerPlayer()
	return Duel.GetFlagEffect(p,m)==0 and Duel.IsPlayerAffectedByEffect(1-p,14000705)
end
function cm.sumsuc(e,tp,eg,ep,ev,re,r,rp)
	Duel.RegisterFlagEffect(tp,m,0,0,0)
end
