--人理之基 张角
function c22021210.initial_effect(c)
	--token
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(22021210,0))
	e1:SetCategory(CATEGORY_SPECIAL_SUMMON+CATEGORY_TOKEN)
	e1:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_O)
	e1:SetProperty(EFFECT_FLAG_CARD_TARGET+EFFECT_FLAG_DELAY)
	e1:SetCode(EVENT_SUMMON_SUCCESS)
	e1:SetCountLimit(1,22021210)
	e1:SetCost(c22021210.tkcost)
	e1:SetTarget(c22021210.tktg)
	e1:SetOperation(c22021210.tkop)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCode(EVENT_SPSUMMON_SUCCESS)
	c:RegisterEffect(e2)
	--attribute change
	local e3=Effect.CreateEffect(c)
	e3:SetDescription(aux.Stringid(22021210,1))
	e3:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O)
	e3:SetCode(EVENT_SPSUMMON_SUCCESS)
	e3:SetRange(LOCATION_MZONE)
	e3:SetCountLimit(1,22021211)
	e3:SetCondition(c22021210.tgcon)
	e3:SetTarget(c22021210.attg)
	e3:SetOperation(c22021210.atop)
	c:RegisterEffect(e3)
	--Atk
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_FIELD)
	e4:SetCode(EFFECT_UPDATE_ATTACK)
	e4:SetRange(LOCATION_MZONE)
	e4:SetTargetRange(LOCATION_MZONE,0)
	e4:SetTarget(c22021210.atktg1)
	e4:SetValue(300)
	c:RegisterEffect(e4)
	local e5=e4:Clone()
	e5:SetTarget(c22021210.atktg2)
	c:RegisterEffect(e5)
	local e6=e4:Clone()
	e6:SetTarget(c22021210.atktg3)
	c:RegisterEffect(e6)
	local e7=e4:Clone()
	e7:SetTarget(c22021210.atktg4)
	c:RegisterEffect(e7)
	local e8=e4:Clone()
	e8:SetTarget(c22021210.atktg5)
	c:RegisterEffect(e8)
	local e9=e4:Clone()
	e9:SetTarget(c22021210.atktg6)
	c:RegisterEffect(e9)
	local e10=e4:Clone()
	e10:SetTarget(c22021210.atktg7)
	c:RegisterEffect(e10)
	--disable
	local e11=Effect.CreateEffect(c)
	e11:SetType(EFFECT_TYPE_FIELD)
	e11:SetRange(LOCATION_MZONE)
	e11:SetTargetRange(0,LOCATION_MZONE)
	e11:SetCode(EFFECT_CANNOT_TRIGGER)
	e11:SetTarget(c22021210.atktg1)
	c:RegisterEffect(e11)
	local e12=e11:Clone()
	e12:SetTarget(c22021210.atktg2)
	c:RegisterEffect(e12)
	local e13=e11:Clone()
	e13:SetTarget(c22021210.atktg3)
	c:RegisterEffect(e13)
	local e14=e11:Clone()
	e14:SetTarget(c22021210.atktg4)
	c:RegisterEffect(e14)
	local e15=e11:Clone()
	e15:SetTarget(c22021210.atktg5)
	c:RegisterEffect(e15)
	local e16=e11:Clone()
	e16:SetTarget(c22021210.atktg6)
	c:RegisterEffect(e16)
	local e17=e11:Clone()
	e17:SetTarget(c22021210.atktg7)
	c:RegisterEffect(e17)
	--attribute change
	local e18=Effect.CreateEffect(c)
	e18:SetDescription(aux.Stringid(22021210,2))
	e18:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O)
	e18:SetCode(EVENT_SPSUMMON_SUCCESS)
	e18:SetRange(LOCATION_GRAVE)
	e18:SetCountLimit(1,22021211)
	e18:SetCondition(c22021210.tgcon1)
	e18:SetCost(c22021210.erecost)
	e18:SetTarget(c22021210.attg)
	e18:SetOperation(c22021210.atop)
	c:RegisterEffect(e18)
end
function c22021210.thcfilter(c)
	return c:IsSetCard(0xff1) and c:IsAbleToRemoveAsCost()
end
function c22021210.tkcost(e,tp,eg,ep,ev,re,r,rp,chk)
	local c=e:GetHandler()
	if chk==0 then return Duel.IsExistingMatchingCard(c22021210.thcfilter,tp,LOCATION_GRAVE,0,1,c) end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_REMOVE)
	local g=Duel.SelectMatchingCard(tp,c22021210.thcfilter,tp,LOCATION_GRAVE,0,1,1,c)
	Duel.Remove(g,POS_FACEUP,REASON_COST)
end
function c22021210.tktg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetLocationCount(tp,LOCATION_MZONE)>0
		and Duel.IsPlayerCanSpecialSummonMonster(tp,22021211,0,TYPES_TOKEN_MONSTER,500,600,1,RACE_MACHINE,ATTRIBUTE_DARK) end
	Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,1,0,0)
	Duel.SetOperationInfo(0,CATEGORY_TOKEN,nil,1,0,0)
end
function c22021210.tkop(e,tp,eg,ep,ev,re,r,rp)
	if Duel.GetLocationCount(tp,LOCATION_MZONE)<=0
		or not Duel.IsPlayerCanSpecialSummonMonster(tp,22021211,0,TYPES_TOKEN_MONSTER,500,600,1,RACE_MACHINE,ATTRIBUTE_DARK) then return end
	local token=Duel.CreateToken(tp,22021211)
	Duel.SpecialSummon(token,0,tp,tp,false,false,POS_FACEUP)
end
function c22021210.cfilter(c,tp)
	return c:IsSummonPlayer(tp) and c:IsPreviousLocation(LOCATION_EXTRA+LOCATION_DECK)
end
function c22021210.tgcon(e,tp,eg,ep,ev,re,r,rp)
	return eg:IsExists(c22021210.cfilter,1,nil,1-tp) or eg:IsExists(c22021210.cfilter,1,nil,tp)
end
function c22021210.attg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.IsExistingMatchingCard(Card.IsFaceup,tp,LOCATION_MZONE,LOCATION_MZONE,1,nil) end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_ATTRIBUTE)
	local rc=Duel.AnnounceAttribute(tp,1,ATTRIBUTE_ALL)
	e:SetLabel(rc)
end
function c22021210.atop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_ADD_ATTRIBUTE)
	e1:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e1:SetValue(e:GetLabel())
	e1:SetReset(RESET_PHASE+PHASE_END)
	Duel.RegisterEffect(e1,tp)
end
function c22021210.atktg1(e,c)
	return c:IsAttribute(ATTRIBUTE_DARK) and (c:IsAttribute(ATTRIBUTE_DEVINE) or c:IsAttribute(ATTRIBUTE_EARTH) or c:IsAttribute(ATTRIBUTE_FIRE) or c:IsAttribute(ATTRIBUTE_LIGHT) or c:IsAttribute(ATTRIBUTE_WATER) or c:IsAttribute(ATTRIBUTE_WIND))
end
function c22021210.atktg2(e,c)
	return c:IsAttribute(ATTRIBUTE_DEVINE) and (c:IsAttribute(ATTRIBUTE_DARK) or c:IsAttribute(ATTRIBUTE_EARTH) or c:IsAttribute(ATTRIBUTE_FIRE) or c:IsAttribute(ATTRIBUTE_LIGHT) or c:IsAttribute(ATTRIBUTE_WATER) or c:IsAttribute(ATTRIBUTE_WIND))
end
function c22021210.atktg3(e,c)
	return c:IsAttribute(ATTRIBUTE_EARTH) and (c:IsAttribute(ATTRIBUTE_DEVINE) or c:IsAttribute(ATTRIBUTE_DARK) or c:IsAttribute(ATTRIBUTE_FIRE) or c:IsAttribute(ATTRIBUTE_LIGHT) or c:IsAttribute(ATTRIBUTE_WATER) or c:IsAttribute(ATTRIBUTE_WIND))
end
function c22021210.atktg4(e,c)
	return c:IsAttribute(ATTRIBUTE_FIRE) and (c:IsAttribute(ATTRIBUTE_DEVINE) or c:IsAttribute(ATTRIBUTE_EARTH) or c:IsAttribute(ATTRIBUTE_DARK) or c:IsAttribute(ATTRIBUTE_LIGHT) or c:IsAttribute(ATTRIBUTE_WATER) or c:IsAttribute(ATTRIBUTE_WIND))
end
function c22021210.atktg5(e,c)
	return c:IsAttribute(ATTRIBUTE_LIGHT) and (c:IsAttribute(ATTRIBUTE_DEVINE) or c:IsAttribute(ATTRIBUTE_EARTH) or c:IsAttribute(ATTRIBUTE_FIRE) or c:IsAttribute(ATTRIBUTE_DARK) or c:IsAttribute(ATTRIBUTE_WATER) or c:IsAttribute(ATTRIBUTE_WIND))
end
function c22021210.atktg6(e,c)
	return c:IsAttribute(ATTRIBUTE_WATER) and (c:IsAttribute(ATTRIBUTE_DEVINE) or c:IsAttribute(ATTRIBUTE_EARTH) or c:IsAttribute(ATTRIBUTE_FIRE) or c:IsAttribute(ATTRIBUTE_LIGHT) or c:IsAttribute(ATTRIBUTE_DARK) or c:IsAttribute(ATTRIBUTE_WIND))
end
function c22021210.atktg7(e,c)
	return c:IsAttribute(ATTRIBUTE_WIND) and (c:IsAttribute(ATTRIBUTE_DEVINE) or c:IsAttribute(ATTRIBUTE_EARTH) or c:IsAttribute(ATTRIBUTE_FIRE) or c:IsAttribute(ATTRIBUTE_LIGHT) or c:IsAttribute(ATTRIBUTE_WATER) or c:IsAttribute(ATTRIBUTE_DARK))
end
function c22021210.erecost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return true end
	Duel.Hint(HINT_CARD,0,22020980)
	Duel.PayLPCost(tp,math.floor(Duel.GetLP(tp)/2))
end
function c22021210.tgcon1(e,tp,eg,ep,ev,re,r,rp)
	return eg:IsExists(c22021210.cfilter,1,nil,1-tp) or eg:IsExists(c22021210.cfilter,1,nil,tp) and Duel.IsPlayerAffectedByEffect(tp,22020980)
end