local m=25000095
local cm=_G["c"..m]
cm.name="一道死去的光"
function cm.initial_effect(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetHintTiming(0,TIMINGS_CHECK_MONSTER+TIMING_END_PHASE)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e2:SetCode(EVENT_ADJUST)
	e2:SetRange(LOCATION_SZONE)
	e2:SetOperation(cm.rmop)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD)
	e3:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e3:SetCode(EFFECT_CANNOT_ACTIVATE)
	e3:SetRange(LOCATION_SZONE)
	e3:SetTargetRange(0,1)
	e3:SetValue(cm.aclimit)
	c:RegisterEffect(e3)
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_FIELD)
	e4:SetCode(EFFECT_DISABLE)
	e4:SetRange(LOCATION_SZONE)
	e4:SetTargetRange(0,LOCATION_MZONE)
	e4:SetTarget(cm.target)
	c:RegisterEffect(e4)
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e5:SetCode(EVENT_ADJUST)
	e5:SetRange(LOCATION_SZONE)
	e5:SetOperation(cm.effop)
	c:RegisterEffect(e5)
end
function cm.rmop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local tc=Duel.GetFirstMatchingCard(function(c,tc)return c:IsAbleToRemove() and c:GetSequence()<5 and tc:GetColumnGroup():IsContains(c)end,tp,LOCATION_MZONE,0,nil,c)
	if tc and Duel.Remove(tc,0,REASON_EFFECT+REASON_TEMPORARY)~=0 and tc:IsLocation(LOCATION_REMOVED) then
		c:RegisterFlagEffect(m,RESET_EVENT+RESETS_STANDARD,0,0)
		tc:RegisterFlagEffect(m,RESET_EVENT+RESETS_STANDARD,0,0,c:GetFlagEffectLabel(m))
		c:CreateRelation(tc,RESET_EVENT+RESETS_STANDARD)
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e1:SetCode(EVENT_ADJUST)
		e1:SetRange(LOCATION_REMOVED)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD)
		e1:SetLabelObject(c)
		e1:SetOperation(cm.retop)
		tc:RegisterEffect(e1,true)
	end
end
function cm.retop(e,tp,eg,ep,ev,re,r,rp)
	local c,tc=e:GetHandler(),e:GetLabelObject()
	if tc:IsRelateToCard(c) and tc:IsLocation(LOCATION_SZONE) and tc:IsFaceup() then return end
	c:ResetFlagEffect(m)
	Duel.ReturnToField(c)
	e:Reset()
end
function cm.aclimit(e,re,tp)
	local tc=re:GetHandler()
	return tc:GetSequence()<5 and tc:IsLocation(LOCATION_MZONE) and re:IsActiveType(TYPE_MONSTER) and e:GetHandler():GetColumnGroup():IsContains(tc)
end
function cm.target(e,c)
	return c:GetSequence()<5 and e:GetHandler():GetColumnGroup():IsContains(c)
end
function cm.effop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local tc=Duel.GetFirstMatchingCard(function(c,tc)return c:GetSequence()>4 and tc:GetColumnGroup():IsContains(c)end,tp,LOCATION_MZONE,LOCATION_MZONE,nil,c)
	if not tc then return end
	local g=Duel.GetMatchingGroup(function(c,tc)return tc:IsRelateToCard(c) and c:GetFlagEffect(m)>0 end,tp,LOCATION_REMOVED,LOCATION_REMOVED,nil,c)
	if #g==0 then return end
	local ec=g:GetMaxGroup(Card.GetFlagEffectLabel,m):GetFirst()
	local cid=tc:ReplaceEffect(ec:GetOriginalCode(),RESET_EVENT+RESETS_STANDARD)
	c:CreateRelation(tc,RESET_EVENT+RESETS_STANDARD)
	local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e1:SetCode(EVENT_ADJUST)
	e1:SetRange(LOCATION_MZONE)
	e1:SetReset(RESET_EVENT+RESETS_STANDARD)
	e1:SetLabel(cid)
	e1:SetLabelObject(c)
	e1:SetOperation(cm.rstop)
	tc:RegisterEffect(e1,true)
end
function cm.rstop(e,tp,eg,ep,ev,re,r,rp)
	local c,tc=e:GetHandler(),e:GetLabelObject()
	if c:GetSequence()>4 and tc:GetColumnGroup():IsContains(c) and tc:IsRelateToCard(c) and tc:IsLocation(LOCATION_SZONE) and tc:IsFaceup() then return end
	local cid=e:GetLabel()
	if cid~=0 then c:ResetEffect(cid,RESET_COPY) end
	e:Reset()
end
