local m=31400108
local cm=_G["c"..m]
cm.name="心影变幻龙"
function cm.initial_effect(c)
	aux.EnablePendulumAttribute(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetRange(LOCATION_PZONE)
	e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_ABSOLUTE_TARGET)
	e1:SetTargetRange(1,0)
	e1:SetLabel(0)
	e1:SetCondition(cm.splimitcon)
	e1:SetTarget(cm.splimit)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetLabel(1)
	e2:SetTargetRange(0,1)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetCategory(CATEGORY_HANDES+CATEGORY_TOHAND)
	e3:SetType(EFFECT_TYPE_IGNITION)
	e3:SetRange(LOCATION_GRAVE)
	e3:SetCountLimit(1,m)
	e3:SetTarget(cm.tg)
	e3:SetOperation(cm.op)
	c:RegisterEffect(e3)
end
function cm.splfilter(c)
	return c:IsPublic() and c:IsRace(RACE_WYRM)
end
function cm.splimitcon(e)
	return Duel.IsExistingMatchingCard(cm.splfilter,e:GetLabel(),LOCATION_HAND,0,1,nil)
end
function cm.splimit(e,c,tp,sumtp,sumpos)
	return not c:IsRace(RACE_WYRM)
end
function cm.thfilter(c)
	return c:IsType(TYPE_MONSTER) and c:IsAbleToHand()
end
function cm.tg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetFieldGroupCount(tp,LOCATION_HAND,0)>0 and Duel.GetFieldGroupCount(tp,0,LOCATION_HAND)>0 and e:GetHandler():IsAbleToHand() and Duel.IsExistingMatchingCard(cm.thfilter,tp,0,LOCATION_GRAVE,1,nil) end
	Duel.SetOperationInfo(0,CATEGORY_HANDES,0,0,PLAYER_ALL,1)
	Duel.SetOperationInfo(0,CATEGORY_TOHAND,nil,1,1-tp,LOCATION_GRAVE)
	Duel.SetOperationInfo(0,CATEGORY_TOHAND,e:GetHandler(),1,0,0)
end
function cm.op(e,tp,eg,ep,ev,re,r,rp)
	local g1=Duel.GetFieldGroup(tp,0,LOCATION_HAND)
	local g2=Duel.GetFieldGroup(tp,LOCATION_HAND,0)
	if #g1==0 or #g2==0 then return end
	local sg=g1:RandomSelect(tp,1)
	sg:Merge(g2:RandomSelect(tp,1))
	Duel.SendtoGrave(sg,REASON_DISCARD+REASON_EFFECT)
	local c=e:GetHandler()
	if not c:IsRelateToEffect(e) then return end
	Duel.BreakEffect()
	if Duel.SendtoHand(c,1-tp,REASON_EFFECT)==0 or not c:IsLocation(LOCATION_HAND) then return end
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_PUBLIC)
	e1:SetReset(RESET_EVENT+RESETS_STANDARD)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCode(EFFECT_CANNOT_TRIGGER)
	c:RegisterEffect(e2)
	local e3=e1:Clone()
	e3:SetCode(EFFECT_CANNOT_SUMMON)
	c:RegisterEffect(e3)
	local e4=e1:Clone()
	e4:SetCode(EFFECT_CANNOT_MSET)
	c:RegisterEffect(e4)
	local gc=Duel.GetFieldGroup(tp,0,LOCATION_GRAVE):FilterSelect(tp,cm.thfilter,1,1,nil):GetFirst()
	if not gc or Duel.SendtoHand(gc,tp,REASON_EFFECT)==0 or not gc:IsLocation(LOCATION_HAND) then return end
	local e5=e1:Clone()
	gc:RegisterEffect(e5)
	local e6=e1:Clone()
	e6:SetCode(EFFECT_CANNOT_TRIGGER)
	gc:RegisterEffect(e6)
	local e7=e1:Clone()
	e7:SetCode(EFFECT_CANNOT_SUMMON)
	gc:RegisterEffect(e7)
	local e8=e1:Clone()
	e8:SetCode(EFFECT_CANNOT_MSET)
	gc:RegisterEffect(e8)
	local e9=e1:Clone()
	e9:SetCode(EFFECT_CHANGE_RACE)
	e9:SetValue(RACE_WYRM)
	gc:RegisterEffect(e9)
end