--Echoes Kernel #Mβ - Burning Memory
local s,id,o=GetID()
Duel.LoadScript("c33741000.lua")
local TOKEN_CODE=33741026
function s.initial_effect(c)
	DEchoes.AddKernelFusion(c,RACE_SPELLCASTER)
	DEchoes.AddGrantTrigger(c,id,s.grant)
end
function s.grant(e,tc)
	local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetDescription(aux.Stringid(id,1))
	e1:SetCategory(CATEGORY_SPECIAL_SUMMON)
	e1:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_O)
	e1:SetProperty(EFFECT_FLAG_DELAY)
	e1:SetCode(EVENT_DESTROYED)
	e1:SetTarget(s.sptg)
	e1:SetOperation(s.spop)
	e1:SetReset(RESET_EVENT+RESETS_STANDARD)
	tc:RegisterEffect(e1,true)
end
function s.sptg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetLocationCount(tp,LOCATION_MZONE)>0
		and Duel.IsPlayerCanSpecialSummonMonster(tp,TOKEN_CODE,DEchoes.SET_DECHOES,TYPE_MONSTER+TYPE_TOKEN,e:GetHandler():GetPreviousAttackOnField(),e:GetHandler():GetPreviousDefenseOnField(),e:GetHandler():GetPreviousLevelOnField(),e:GetHandler():GetPreviousRaceOnField(),e:GetHandler():GetPreviousAttributeOnField()) end
	Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,1,tp,0)
end
function s.spop(e,tp,eg,ep,ev,re,r,rp)
	if Duel.GetLocationCount(tp,LOCATION_MZONE)<=0 then return end
	local c=e:GetHandler()
	local token=Duel.CreateToken(tp,TOKEN_CODE)
	if Duel.SpecialSummonStep(token,0,tp,tp,false,false,POS_FACEUP) then
		local code=c:GetOriginalCode()
		local atk=c:GetPreviousAttackOnField()
		local def=c:GetPreviousDefenseOnField()
		local lv=c:GetPreviousLevelOnField()
		local race=c:GetPreviousRaceOnField()
		local att=c:GetPreviousAttributeOnField()
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_CHANGE_CODE)
		e1:SetValue(code)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD)
		token:RegisterEffect(e1,true)
		local e2=e1:Clone()
		e2:SetCode(EFFECT_SET_ATTACK)
		e2:SetValue(atk)
		token:RegisterEffect(e2,true)
		local e3=e1:Clone()
		e3:SetCode(EFFECT_SET_DEFENSE)
		e3:SetValue(def)
		token:RegisterEffect(e3,true)
		local e4=e1:Clone()
		e4:SetCode(EFFECT_CHANGE_LEVEL)
		e4:SetValue(lv)
		token:RegisterEffect(e4,true)
		local e5=e1:Clone()
		e5:SetCode(EFFECT_CHANGE_RACE)
		e5:SetValue(race)
		token:RegisterEffect(e5,true)
		local e6=e1:Clone()
		e6:SetCode(EFFECT_CHANGE_ATTRIBUTE)
		e6:SetValue(att)
		token:RegisterEffect(e6,true)
	end
	Duel.SpecialSummonComplete()
end
