--随波而涌的潮鸣
function c33710917.initial_effect(c)
	--xyz summon
	aux.AddXyzProcedure(c,nil,4,2)
	c:EnableReviveLimit() 
	--token
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(33710917,0))
	e1:SetCategory(CATEGORY_SPECIAL_SUMMON+CATEGORY_TOKEN)
	e1:SetType(EFFECT_TYPE_QUICK_O)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetCountLimit(1)
	e1:SetRange(LOCATION_MZONE)
	e1:SetHintTiming(0,TIMING_BATTLE_START+TIMING_END_PHASE)
	e1:SetCost(c33710917.spcost)
	e1:SetTarget(c33710917.sptg)
	e1:SetOperation(c33710917.spop)
	c:RegisterEffect(e1)
	--ATKUP
	local e2=Effect.CreateEffect(c)
	e2:SetCategory(CATEGORY_ATKCHANGE)
	e2:SetDescription(aux.Stringid(33710917,0))
	e2:SetType(EFFECT_TYPE_IGNITION)
	e2:SetRange(LOCATION_MZONE)
	e2:SetCost(c33710917.cost)
	e2:SetOperation(c33710917.operation)
	c:RegisterEffect(e2)
end
function c33710917.cost1(e,c,tp,st)
	return Duel.IsExistingMatchingCard(Card.IsType,tp,LOCATION_ONFIELD,0,1,nil,TYPE_TOKEN)
end
function c33710917.spcost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return e:GetHandler():CheckRemoveOverlayCard(tp,1,REASON_COST) end
	e:GetHandler():RemoveOverlayCard(tp,1,1,REASON_COST)
end
function c33710917.sptg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetLocationCount(tp,LOCATION_MZONE)>0
		and Duel.IsPlayerCanSpecialSummonMonster(tp,33710919,0,0x4011,0,0,4,nil,nil) end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_ATTRIBUTE)
	local rc=Duel.AnnounceAttribute(tp,1,0xffff)
	e:SetLabel(rc)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_RACE)
	local rac=Duel.AnnounceRace(tp,1,RACE_ALL)
	e:SetLabel(rc)
	Duel.SetTargetPlayer(1-tp)
	Duel.SetTargetParam(rac)
	Duel.SetOperationInfo(0,CATEGORY_TOKEN,nil,1,0,0)
	Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,1,0,0)
end
function c33710917.spop(e,tp,eg,ep,ev,re,r,rp)
	local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetTargetRange(1,0)
	e1:SetLabel(rc)
	e1:SetTarget(c33710917.splimit1)
	e1:SetReset(RESET_PHASE+PHASE_END)
	Duel.RegisterEffect(e1,tp)
	local e2=Effect.CreateEffect(e:GetHandler())
	e2:SetType(EFFECT_TYPE_FIELD)
	e2:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
	e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e2:SetTargetRange(1,0)
	e2:SetLabel(rac)
	e2:SetTarget(c33710917.splimit2)
	e2:SetReset(RESET_PHASE+PHASE_END)
	Duel.RegisterEffect(e2,tp)
	local rc=e:GetLabel()
	local p,rac=Duel.GetChainInfo(0,CHAININFO_TARGET_PLAYER,CHAININFO_TARGET_PARAM)
	if Duel.GetLocationCount(tp,LOCATION_MZONE)<=0
		or not Duel.IsPlayerCanSpecialSummonMonster(tp,33710919,0,0x4011,0,0,4,rac,rc) then return end
	local token=Duel.CreateToken(tp,33710919)
	Duel.SpecialSummonStep(token,0,tp,tp,false,false,POS_FACEUP)
	local e11=Effect.CreateEffect(e:GetHandler())
	e11:SetType(EFFECT_TYPE_SINGLE)
	e11:SetCode(EFFECT_CHANGE_ATTRIBUTE)
	e11:SetValue(rc)
	e11:SetReset(RESET_EVENT+RESETS_STANDARD)
	token:RegisterEffect(e11)
	local e21=Effect.CreateEffect(e:GetHandler())
	e21:SetType(EFFECT_TYPE_SINGLE)
	e21:SetCode(EFFECT_CHANGE_RACE)
	e21:SetValue(rac)
	e21:SetReset(RESET_EVENT+RESETS_STANDARD)
	token:RegisterEffect(e21)
	Duel.SpecialSummonComplete()
end
function c33710917.splimit1(e,c,tp,sumtp,sumpos)
	return not c:IsAttribute(e:GetLabel())
end
function c33710917.splimit2(e,c,tp,sumtp,sumpos)
	return not c:IsRace(e:GetLabel())
end
function c33710917.cost(e,tp,eg,ep,ev,re,r,rp,chk)
	local sg=e:GetHandler():GetOverlayGroup()
	sg:KeepAlive()
	if chk==0 then return e:GetHandler():CheckRemoveOverlayCard(tp,1,REASON_COST) and Duel.IsExistingMatchingCard(Card.IsType,tp,LOCATION_MZONE,0,1,nil,TYPE_TOKEN) end
	e:GetHandler():RemoveOverlayCard(tp,1,1,REASON_COST)
	sg:Remove(c33710917.ff,nil,e:GetHandler():GetOverlayGroup())  
	e:SetLabelObject(sg)
end
function c33710917.ff(c,g)
	return g:IsContains(c)
end
function c33710917.operation(e,tp,eg,ep,ev,re,r,rp)
	local sg=e:GetLabelObject()
	local g=Duel.GetMatchingGroup(Card.IsCode,tp,LOCATION_MZONE,0,nil,33710919)
	local tc=g:GetFirst()
	while tc do
		local e1=Effect.CreateEffect(e:GetHandler())
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_UPDATE_ATTACK)
		e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e1:SetValue(sg:GetFirst():GetAttack())
		e1:SetReset(RESET_EVENT+RESETS_STANDARD)
		tc:RegisterEffect(e1)
		local e2=e1:Clone()
		e2:SetCode(EFFECT_UPDATE_DEFENSE)
		e2:SetValue(sg:GetFirst():GetDefense())
		tc:RegisterEffect(e2)
		tc=g:GetNext()
	end
end