--紧闭的恋之瞳
function c37900034.initial_effect(c)
	c:EnableReviveLimit()
	aux.AddXyzProcedureLevelFree(c,c37900034.mfilter,c37900034.xyzcheck,2,2)
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(37900034,0))
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetProperty(EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_IGNORE_IMMUNE)
	e1:SetCode(EFFECT_SPSUMMON_PROC)
	e1:SetRange(LOCATION_EXTRA)
	e1:SetCondition(c37900034.con)
	e1:SetOperation(c37900034.op)
	e1:SetValue(SUMMON_TYPE_XYZ)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_ACTIVATE)
	e2:SetCode(EVENT_ATTACK_ANNOUNCE)
	e2:SetRange(LOCATION_MZONE)
	e2:SetCondition(c37900034.con2)
	e2:SetOperation(c37900034.op2)
	c:RegisterEffect(e2)	
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e3:SetCode(EFFECT_IGNORE_BATTLE_TARGET)
	e3:SetRange(LOCATION_MZONE)
	e3:SetCondition(c37900034.con3)
	e3:SetValue(1)
	c:RegisterEffect(e3)
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_SINGLE)
	e4:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e4:SetCode(EFFECT_CANNOT_BE_EFFECT_TARGET)
	e4:SetRange(LOCATION_MZONE)
	e4:SetCondition(c37900034.con3)
	e4:SetValue(1)
	c:RegisterEffect(e4)
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_SINGLE)
	e5:SetCode(EFFECT_PIERCE)
	c:RegisterEffect(e5)
	local e6=Effect.CreateEffect(c)
	e6:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e6:SetCode(EVENT_PRE_BATTLE_DAMAGE)
	e6:SetCondition(c37900034.con6)
	e6:SetOperation(c37900034.op6)
	c:RegisterEffect(e6)
end
function c37900034.mfilter(c,xyzc)
	return c:IsXyzType(TYPE_XYZ)
end
function c37900034.xyzcheck(g)
	return g:GetClassCount(Card.GetRank)==1
end
function c37900034.q(c)
	return c:IsCode(37900004) and c:IsAbleToRemoveAsCost()
end
function c37900034.con(e,c)
	if c==nil then return true end
	local tp=e:GetHandler():GetControler()
	return Duel.IsExistingMatchingCard(c37900034.q,tp,LOCATION_GRAVE,0,1,nil) and Duel.IsCanRemoveCounter(tp,1,0,0x389,20,REASON_COST) and (Duel.GetLocationCount(tp,LOCATION_MZONE)>0 or Duel.GetLocationCountFromEx(tp)>0) 
end
function c37900034.op(e,tp,eg,ep,ev,re,r,rp)
	local p=e:GetHandler():GetControler()
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_REMOVE)
	local g=Duel.SelectMatchingCard(p,c37900034.q,p,LOCATION_GRAVE,0,1,1,nil)	
	Duel.RemoveCounter(p,1,0,0x389,20,REASON_COST)
	Duel.Remove(g,POS_FACEUP,REASON_COST)
end
function c37900034.con2(e,tp,eg,ep,ev,re,r,rp)
	return tp~=Duel.GetTurnPlayer() and e:GetHandler():IsPosition(POS_FACEUP_ATTACK)
end
function c37900034.op2(e,tp,eg,ep,ev,re,r,rp)
	if Duel.NegateAttack() then
	local lp1=Duel.GetLP(tp)
	local lp2=Duel.GetLP(1-tp)
	Duel.SetLP(tp,lp1-514)
	Duel.SetLP(1-tp,lp2-514)
	end
end
function c37900034.con3(e,tp,eg,ep,ev,re,r,rp)
	return e:GetHandler():IsPosition(POS_FACEUP_DEFENSE)
end
function c37900034.con6(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local b=Duel.GetAttackTarget()
	return ep~=tp and b and c==Duel.GetAttacker() and not b:IsPosition(POS_FACEUP_ATTACK)
end
function c37900034.op6(e,tp,eg,ep,ev,re,r,rp)
	Duel.ChangeBattleDamage(ep,ev*0.5)
end