if not require and dofile then function require(str) return dofile(str..".lua") end end
if not pcall(function() require("expansions/script/c53702500") end) then require("script/c53702500") end
local s,id,o=GetID()
function s.initial_effect(c)
	SNNM.ATTSeries(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetRange(LOCATION_MZONE)
	e1:SetTargetRange(1,0)
	e1:SetCode(EFFECT_CANNOT_DISCARD_HAND)
	e1:SetCondition(SNNM.ATTSerieslockcon(0,ATTRIBUTE_WATER))
	e1:SetValue(1)
	c:RegisterEffect(e1)
	local e1_1=e1:Clone()
	e1_1:SetTargetRange(0,1)
	e1_1:SetCondition(SNNM.ATTSerieslockcon(1,ATTRIBUTE_WATER))
	c:RegisterEffect(e1_1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD)
	e2:SetProperty(EFFECT_FLAG_SET_AVAILABLE+EFFECT_FLAG_IGNORE_RANGE+EFFECT_FLAG_IGNORE_IMMUNE)
	e2:SetCode(EFFECT_CANNOT_TO_GRAVE_AS_COST)
	e2:SetRange(LOCATION_MZONE)
	e2:SetTargetRange(0xff,0)
	e2:SetCondition(SNNM.ATTSerieslockcon(0,ATTRIBUTE_WATER))
	e2:SetValue(1)
	c:RegisterEffect(e2)
	local e2_1=e2:Clone()
	e2_1:SetTargetRange(0,0xff)
	e2_1:SetCondition(SNNM.ATTSerieslockcon(1,ATTRIBUTE_WATER))
	c:RegisterEffect(e2_1)
end
