local m=53799244
local cm=_G["c"..m]
cm.name="力之受取"
function cm.initial_effect(c)
	local e1=Effect.CreateEffect(c)
	e1:SetCategory(CATEGORY_EQUIP)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetProperty(EFFECT_FLAG_CARD_TARGET+EFFECT_FLAG_CONTINUOUS_TARGET)
	e1:SetTarget(cm.target)
	e1:SetOperation(cm.operation)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetCode(EFFECT_EQUIP_LIMIT)
	e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e2:SetValue(function(e,c)return c:IsSummonType(SUMMON_TYPE_SYNCHRO)end)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_EQUIP)
	e3:SetCode(EFFECT_XYZ_LEVEL)
	e3:SetValue(function(e,c,rc)return c:GetLevel()+0x10000*e:GetLabel()end)
	e3:SetLabel(1)
	c:RegisterEffect(e3)
	local e4=e3:Clone()
	e4:SetLabel(2)
	c:RegisterEffect(e4)
	local e5=e3:Clone()
	e5:SetLabel(3)
	c:RegisterEffect(e5)
	local e6=e3:Clone()
	e6:SetLabel(4)
	c:RegisterEffect(e6)
	local e7=e3:Clone()
	e7:SetLabel(5)
	c:RegisterEffect(e7)
	local e8=e3:Clone()
	e8:SetLabel(6)
	c:RegisterEffect(e8)
	local e9=e3:Clone()
	e9:SetLabel(7)
	c:RegisterEffect(e9)
	local e10=e3:Clone()
	e10:SetLabel(8)
	c:RegisterEffect(e10)
	local e11=e3:Clone()
	e11:SetLabel(9)
	c:RegisterEffect(e11)
	local e12=e3:Clone()
	e12:SetLabel(10)
	c:RegisterEffect(e12)
	local e13=e3:Clone()
	e13:SetLabel(11)
	c:RegisterEffect(e13)
	local e14=e3:Clone()
	e14:SetLabel(12)
	c:RegisterEffect(e14)
end
function cm.filter(c)
	return c:IsFaceup() and c:IsSummonType(SUMMON_TYPE_SYNCHRO)
end
function cm.target(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chkc then return chkc:IsLocation(LOCATION_MZONE) and cm.filter(chkc) end
	if chk==0 then return Duel.IsExistingTarget(cm.filter,tp,LOCATION_MZONE,LOCATION_MZONE,1,nil) end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_EQUIP)
	Duel.SelectTarget(tp,cm.filter,tp,LOCATION_MZONE,LOCATION_MZONE,1,1,nil)
	Duel.SetOperationInfo(0,CATEGORY_EQUIP,e:GetHandler(),1,0,0)
end
function cm.operation(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local tc=Duel.GetFirstTarget()
	if c:IsRelateToEffect(e) and tc:IsRelateToEffect(e) and tc:IsFaceup() then Duel.Equip(tp,c,tc) end
end
