local m=53716007
local cm=_G["c"..m]
cm.name="断片折光 幻想死阶"
if not pcall(function() require("expansions/script/c53702500") end) then require("script/c53702500") end
function cm.initial_effect(c)
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(53702500,0))
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_CHAINING)
	e1:SetProperty(EFFECT_FLAG_DELAY)
	e1:SetCountLimit(1,m)
	e1:SetCondition(function(e,tp,eg,ep,ev,re,r,rp)return ep~=tp and re:IsActiveType(TYPE_SPELL+TYPE_TRAP)end)
	e1:SetTarget(SNNM.FanippetTrapSPTarget(m,1900,700,RACE_ZOMBIE,ATTRIBUTE_LIGHT))
	e1:SetOperation(SNNM.FanippetTrapSPOperation(800,m,1900,700,RACE_ZOMBIE,ATTRIBUTE_LIGHT))
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetRange(LOCATION_GRAVE)
	c:RegisterEffect(e2)
	local e21=e1:Clone()
	e21:SetCode(EVENT_FREE_CHAIN)
	e21:SetProperty(0)
	e21:SetCondition(function(e)return false end)
	c:RegisterEffect(e21)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetCode(EFFECT_TRAP_ACT_IN_HAND)
	c:RegisterEffect(e3)
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_FIELD)
	e4:SetCode(EFFECT_ACTIVATE_COST)
	e4:SetRange(LOCATION_GRAVE)
	e4:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e4:SetTargetRange(1,0)
	e4:SetCost(SNNM.GraveActCostchk)
	e4:SetTarget(SNNM.GraveActCostTarget)
	e4:SetOperation(SNNM.GraveActCostOp)
	c:RegisterEffect(e4)
	local e5=Effect.CreateEffect(c)
	e5:SetCategory(CATEGORY_DECKDES)
	e5:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_F)
	e5:SetCode(EVENT_RELEASE)
	e5:SetProperty(EFFECT_FLAG_DAMAGE_STEP)
	e5:SetCondition(SNNM.FanippetTrapTGCondition)
	e5:SetTarget(SNNM.FanippetTrapTGTarget)
	e5:SetOperation(SNNM.FanippetTrapTGOperation)
	c:RegisterEffect(e5)
end
