local m=53716017
local cm=_G["c"..m]
cm.name="残滓离光 妄想天崖"
cm.Snnm_Ef_Rst=true
if not require and dofile then function require(str) return dofile(str..".lua") end end
if not pcall(function() require("expansions/script/c53702500") end) then require("script/c53702500") end
function cm.initial_effect(c)
	--SNNM.AllEffectReset(c)
	c:EnableReviveLimit()
	local e0=Effect.CreateEffect(c)
	e0:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e0:SetType(EFFECT_TYPE_SINGLE)
	e0:SetCode(EFFECT_SPSUMMON_CONDITION)
	e0:SetValue(aux.FALSE)
	c:RegisterEffect(e0)
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(m,0))
	e1:SetCategory(CATEGORY_SPECIAL_SUMMON)
	e1:SetType(EFFECT_TYPE_QUICK_O)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetRange(LOCATION_EXTRA)
	e1:SetHintTiming(0,TIMINGS_CHECK_MONSTER+TIMING_END_PHASE)
	e1:SetCountLimit(1,m)
	e1:SetCost(cm.cost)
	--e1:SetTarget(cm.tg)
	--e1:SetOperation(cm.op)
	c:RegisterEffect(e1)
	cm.Lustruin=e1
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD)
	e2:SetCode(EFFECT_ACTIVATE_COST)
	e2:SetRange(LOCATION_EXTRA)
	e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e2:SetTargetRange(1,1)
	e2:SetLabelObject(e1)
	e2:SetCondition(cm.accon)
	e2:SetTarget(cm.actarget)
	e2:SetOperation(cm.acop)
	c:RegisterEffect(e2)
	local ew=Effect.CreateEffect(c)
	ew:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	ew:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	ew:SetProperty(EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
	ew:SetRange(0xff)
	--ew:SetOperation(cm.down)
	ew:SetCountLimit(1,EFFECT_COUNT_CODE_DUEL+m)
	c:RegisterEffect(ew)
	local ex=Effect.CreateEffect(c)
	ex:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	ex:SetCode(EVENT_ADJUST)
	ex:SetProperty(EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
	ex:SetRange(0xff)
	ex:SetOperation(cm.reset)
	c:RegisterEffect(ex)
end
