--融合变身库
FusionA=FusionA or {}
FusionA.loaded_metatable_list={}

function FusionA.Change(c,code)
	local token=Duel.CreateToken(tp,code)
	c:SetCardData(CARDDATA_CODE,code)
	c:ReplaceEffect(60002381,0)
	token.initial_effect(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_REMOVE_TYPE)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_IGNORE_IMMUNE)
	e1:SetRange(0xff)
	e1:SetValue(0xfffffff)
	c:RegisterEffect(e1)
	if token:IsType(TYPE_MONSTER) then
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_IGNORE_IMMUNE)
		e1:SetCode(EFFECT_CHANGE_ATTRIBUTE)
		e1:SetValue(token:GetAttribute())
		e1:SetRange(0xff)
		c:RegisterEffect(e1)
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_IGNORE_IMMUNE)
		e1:SetCode(EFFECT_CHANGE_RACE)
		e1:SetValue(token:GetRace())
		e1:SetRange(0xff)
		c:RegisterEffect(e1)
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_IGNORE_IMMUNE)
		e1:SetCode(EFFECT_CHANGE_TYPE)
		e1:SetValue(token:GetType()-TYPE_TOKEN)
		e1:SetRange(0xff)
		c:RegisterEffect(e1)
		if c:IsType(TYPE_XYZ) then
			local e1=Effect.CreateEffect(c)
			e1:SetType(EFFECT_TYPE_SINGLE)
			e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_IGNORE_IMMUNE)
			e1:SetCode(EFFECT_CHANGE_RANK)
			e1:SetValue(token:GetRank())
			e1:SetRange(0xff)
			c:RegisterEffect(e1)
		elseif c:IsType(TYPE_LINK) then
			local e1=Effect.CreateEffect(c)
			e1:SetType(EFFECT_TYPE_SINGLE)
			e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_IGNORE_IMMUNE)
			e1:SetCode(EFFECT_CHANGE_LINK)
			e1:SetValue(token:GetLink())
			e1:SetRange(0xff)
			c:RegisterEffect(e1)
			if token:IsLinkMarker(0x001) then
				local e1=Effect.CreateEffect(c)
				e1:SetType(EFFECT_TYPE_SINGLE)
				e1:SetRange(0xff)
				e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
				e1:SetCode(EFFECT_ADD_LINK_MARKER_KOISHI)
				e1:SetValue(0x001)
				c:RegisterEffect(e1)
			elseif token:IsLinkMarker(0x002) then
				local e1=Effect.CreateEffect(c)
				e1:SetType(EFFECT_TYPE_SINGLE)
				e1:SetRange(0xff)
				e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
				e1:SetCode(EFFECT_ADD_LINK_MARKER_KOISHI)
				e1:SetValue(0x002)
				c:RegisterEffect(e1)
			elseif token:IsLinkMarker(0x004) then
				local e1=Effect.CreateEffect(c)
				e1:SetType(EFFECT_TYPE_SINGLE)
				e1:SetRange(0xff)
				e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
				e1:SetCode(EFFECT_ADD_LINK_MARKER_KOISHI)
				e1:SetValue(0x008)
				c:RegisterEffect(e1)
			elseif token:IsLinkMarker(0x008) then
				local e1=Effect.CreateEffect(c)
				e1:SetType(EFFECT_TYPE_SINGLE)
				e1:SetRange(0xff)
				e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
				e1:SetCode(EFFECT_ADD_LINK_MARKER_KOISHI)
				e1:SetValue(0x008)
				c:RegisterEffect(e1)
			elseif token:IsLinkMarker(0x020) then
				local e1=Effect.CreateEffect(c)
				e1:SetType(EFFECT_TYPE_SINGLE)
				e1:SetRange(0xff)
				e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
				e1:SetCode(EFFECT_ADD_LINK_MARKER_KOISHI)
				e1:SetValue(0x020)
				c:RegisterEffect(e1)
			elseif token:IsLinkMarker(0x040) then
				local e1=Effect.CreateEffect(c)
				e1:SetType(EFFECT_TYPE_SINGLE)
				e1:SetRange(0xff)
				e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
				e1:SetCode(EFFECT_ADD_LINK_MARKER_KOISHI)
				e1:SetValue(0x040)
				c:RegisterEffect(e1)
			elseif token:IsLinkMarker(0x080) then
				local e1=Effect.CreateEffect(c)
				e1:SetType(EFFECT_TYPE_SINGLE)
				e1:SetRange(0xff)
				e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
				e1:SetCode(EFFECT_ADD_LINK_MARKER_KOISHI)
				e1:SetValue(0x080)
				c:RegisterEffect(e1)
			elseif token:IsLinkMarker(0x100) then
				local e1=Effect.CreateEffect(c)
				e1:SetType(EFFECT_TYPE_SINGLE)
				e1:SetRange(0xff)
				e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
				e1:SetCode(EFFECT_ADD_LINK_MARKER_KOISHI)
				e1:SetValue(0x100)
				c:RegisterEffect(e1)
			end
		else
			local e1=Effect.CreateEffect(c)
			e1:SetType(EFFECT_TYPE_SINGLE)
			e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_IGNORE_IMMUNE)
			e1:SetCode(EFFECT_CHANGE_LEVEL)
			e1:SetValue(token:GetLevel())
			e1:SetRange(0xff)
			c:RegisterEffect(e1)
		end
		if c:IsType(TYPE_PENDULUM) then
			local e1=Effect.CreateEffect(c)
			e1:SetType(EFFECT_TYPE_SINGLE)
			e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_IGNORE_IMMUNE)
			e1:SetCode(EFFECT_CHANGE_LSCALE)
			e1:SetValue(token:GetLeftScale())
			e1:SetRange(0xff)
			c:RegisterEffect(e1)
			local e1=Effect.CreateEffect(c)
			e1:SetType(EFFECT_TYPE_SINGLE)
			e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_IGNORE_IMMUNE)
			e1:SetCode(EFFECT_CHANGE_RSCALE)
			e1:SetValue(token:GetRightScale())
			e1:SetRange(0xff)
			c:RegisterEffect(e1)
		end
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_SET_BASE_ATTACK)
		e1:SetValue(token:GetBaseAttack())
		c:RegisterEffect(e1)
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_SET_BASE_DEFENSE)
		e1:SetValue(token:GetBaseDefense())
		c:RegisterEffect(e1)
	else
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_FLAG_IGNORE_IMMUNE)
		e1:SetCode(EFFECT_CHANGE_TYPE)
		e1:SetValue(token:GetType())
		e1:SetRange(0xff)
		c:RegisterEffect(e1)
	end
end