--人偶·星见亚砂
function c74515847.initial_effect(c)
	aux.EnableDualAttribute(c)
	--sort
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(74515847,0))
	e1:SetType(EFFECT_TYPE_IGNITION)
	e1:SetCondition(aux.IsDualState)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCountLimit(1)
	e1:SetTarget(c74515847.sttg)
	e1:SetOperation(c74515847.stop)
	c:RegisterEffect(e1)
end
function c74515847.sttg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetFieldGroupCount(tp,0,LOCATION_DECK)>2 end
end
function c74515847.stop(e,tp,eg,ep,ev,re,r,rp)
	Duel.SortDecktop(tp,1-tp,3)
	Duel.BreakEffect()
	if Duel.SelectYesNo(tp,aux.Stringid(74515847,1)) then
		Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_CODE)
		local ac=Duel.AnnounceCard(tp)
		local c=e:GetHandler()
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_FIELD)
		e1:SetCode(EFFECT_DISABLE)
		e1:SetTargetRange(LOCATION_ONFIELD,LOCATION_ONFIELD)
		e1:SetTarget(c74515847.distg)
		e1:SetLabel(ac)
		e1:SetReset(RESET_PHASE+PHASE_END,2)
		Duel.RegisterEffect(e1,tp)
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e2:SetCode(EVENT_CHAIN_SOLVING)
		e2:SetCondition(c74515847.discon)
		e2:SetOperation(c74515847.disop)
		e2:SetLabel(ac)
		e2:SetReset(RESET_PHASE+PHASE_END,2)
		Duel.RegisterEffect(e2,tp)
		local e3=Effect.CreateEffect(c)
		e3:SetType(EFFECT_TYPE_FIELD)
		e3:SetCode(EFFECT_DISABLE_TRAPMONSTER)
		e3:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
		e3:SetTarget(c74515847.distg)
		e3:SetLabel(ac)
		e3:SetReset(RESET_PHASE+PHASE_END,2)
		Duel.RegisterEffect(e3,tp)
	end
end
function c74515847.distg(e,c)
	local ac=e:GetLabel(ac)
	return c:IsOriginalCodeRule(ac)
end
function c74515847.discon(e,tp,eg,ep,ev,re,r,rp)
	local ac=e:GetLabel(ac)
	return re:GetHandler():IsOriginalCodeRule(ac)
end
function c74515847.disop(e,tp,eg,ep,ev,re,r,rp)
	Duel.NegateEffect(ev)
end
