--罗德岛·先锋干员-格拉尼
function c79029024.initial_effect(c)
   aux.AddLinkProcedure(c,aux.FilterBoolFunction(Card.IsLinkType,TYPE_EFFECT),2)
	c:EnableReviveLimit()
	--to hand
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(79029024,1))
	e1:SetCategory(CATEGORY_TOHAND+CATEGORY_SEARCH)
	e1:SetType(EFFECT_TYPE_TRIGGER_O+EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_DELAY)
	e1:SetCode(EVENT_SPSUMMON_SUCCESS)
	e1:SetCountLimit(1,79029024)
	e1:SetTarget(c79029024.thtg)
	e1:SetOperation(c79029024.thop)
	c:RegisterEffect(e1)
	--indes
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD)
	e2:SetCode(EFFECT_INDESTRUCTABLE_BATTLE)
	e2:SetRange(LOCATION_MZONE)
	e2:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e2:SetTarget(c79029024.indtg)
	e2:SetValue(1)
	c:RegisterEffect(e2)
	local e3=e2:Clone()
	e3:SetCode(EFFECT_INDESTRUCTABLE_EFFECT)
	c:RegisterEffect(e3)
	--effect gain
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e4:SetCode(EVENT_BE_MATERIAL)
	e4:SetCondition(c79029024.efcon)
	e4:SetOperation(c79029024.efop)
	c:RegisterEffect(e4)
end
function c79029024.thfilter(c)
	return c:IsSetCard(0x1901) and c:IsAbleToHand()
end
function c79029024.thtg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.IsExistingMatchingCard(c79029024.thfilter,tp,LOCATION_DECK,0,1,nil) end
	Duel.SetOperationInfo(0,CATEGORY_TOHAND,nil,1,tp,LOCATION_DECK)
end
function c79029024.thop(e,tp,eg,ep,ev,re,r,rp)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_ATOHAND)
	local g=Duel.SelectMatchingCard(tp,c79029024.thfilter,tp,LOCATION_DECK,0,1,1,nil)
	if g:GetCount()>0 then
		Duel.SendtoHand(g,nil,REASON_EFFECT)
		Duel.ConfirmCards(1-tp,g)
	Debug.Message("各位，让我们把胜利带回罗德岛！")
	Duel.Hint(HINT_SOUND,0,aux.Stringid(79029024,2))
	end
end
function c79029024.indtg(e,c)
	return e:GetHandler():GetLinkedGroup():IsContains(c)
end
function c79029024.efcon(e,tp,eg,ep,ev,re,r,rp)
	local ec=e:GetHandler():GetReasonCard()
	return (ec:IsSummonType(SUMMON_TYPE_XYZ) or ec:IsSummonType(SUMMON_TYPE_FUSION) or ec:IsSummonType(SUMMON_TYPE_LINK)) and ec:IsSetCard(0xa900)
end
function c79029024.efop(e,tp,eg,ep,ev,re,r,rp)
	Duel.Hint(HINT_CARD,0,79029024)
	local c=e:GetHandler()
	local rc=c:GetReasonCard()
		local e1=Effect.CreateEffect(rc)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_ATTACK_ALL)
		e1:SetValue(1)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_DISABLE)
		rc:RegisterEffect(e1,true) 
		local e2=Effect.CreateEffect(rc)
		e2:SetType(EFFECT_TYPE_FIELD)
		e2:SetCode(EFFECT_CANNOT_SELECT_BATTLE_TARGET)
		e2:SetRange(LOCATION_MZONE)
		e2:SetTargetRange(0,LOCATION_MZONE)
		e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_DISABLE)
		e2:SetValue(c79029024.catktg)
		rc:RegisterEffect(e2,true)
		rc:RegisterFlagEffect(79029024,RESET_EVENT+RESETS_STANDARD,EFFECT_FLAG_CLIENT_HINT,1,0,aux.Stringid(79029024,0))
	Debug.Message("以我的枪尖开路！")
	Duel.Hint(HINT_SOUND,0,aux.Stringid(79029024,3))
end
function c79029024.catktg(e,c)
	return c:IsFaceup() and not c:GetMaterial():IsExists(Card.IsCode,1,nil,79029024)
end