function c82221044.initial_effect(c)  
	--end battle phase  
	local e1=Effect.CreateEffect(c)   
	e1:SetType(EFFECT_TYPE_QUICK_O)  
	e1:SetCode(EVENT_FREE_CHAIN)  
	e1:SetRange(LOCATION_GRAVE)  
	e1:SetCountLimit(1,82221044)  
	e1:SetCost(aux.bfgcost)  
	e1:SetOperation(c82221044.operation)  
	c:RegisterEffect(e1)  
end  
function c82221044.operation(e,tp,eg,ep,ev,re,r,rp)  
	local e1=Effect.CreateEffect(e:GetHandler())  
	e1:SetType(EFFECT_TYPE_FIELD)  
	e1:SetCode(EFFECT_CHANGE_DAMAGE)  
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)  
	e1:SetTargetRange(1,0)  
	e1:SetValue(0)  
	e1:SetReset(RESET_PHASE+PHASE_END,1)  
	Duel.RegisterEffect(e1,tp)  
	local e2=e1:Clone()  
	e2:SetCode(EFFECT_NO_EFFECT_DAMAGE)  
	e2:SetReset(RESET_PHASE+PHASE_END,1)  
	Duel.RegisterEffect(e2,tp)  
end  