function c82224444.initial_effect(c)	
	local e1=Effect.CreateEffect(c)  
	e1:SetCategory(CATEGORY_DESTROY)  
	e1:SetType(EFFECT_TYPE_QUICK_O)  
	e1:SetCode(EVENT_FREE_CHAIN)  
	e1:SetHintTiming(TIMINGS_CHECK_MONSTER)  
	e1:SetRange(LOCATION_HAND)  
	e1:SetCountLimit(1,82224444)  
	e1:SetCost(c82224444.cost) 
	e1:SetTarget(c82224444.target)
	e1:SetOperation(c82224444.operation)  
	c:RegisterEffect(e1)  
end  
function c82224444.cost(e,tp,eg,ep,ev,re,r,rp,chk)  
	if chk==0 then return e:GetHandler():IsDiscardable(REASON_COST) end
	Duel.Hint(HINT_SELECTMSG,tp,aux.Stringid(82224444,0))  
	Duel.SelectOption(tp,1213)  
	Duel.SendtoGrave(e:GetHandler(),REASON_COST+REASON_DISCARD)  
end  
function c82224444.filter(c)  
	return c:IsLevel(4) and c:IsFaceup()  
end  
function c82224444.target(e,tp,eg,ep,ev,re,r,rp,chk)  
	if chk==0 then return Duel.IsExistingMatchingCard(c82224444.filter,tp,LOCATION_MZONE,LOCATION_MZONE,1,nil) end  
	local sg=Duel.GetMatchingGroup(c82224444.filter,tp,LOCATION_MZONE,LOCATION_MZONE,nil)  
	Duel.SetOperationInfo(0,CATEGORY_DESTROY,sg,sg:GetCount(),0,0)  
end  
function c82224444.operation(e,tp,eg,ep,ev,re,r,rp)
	local sg=Duel.SelectMatchingCard(tp,c82224444.filter,tp,LOCATION_MZONE,LOCATION_MZONE,1,1,nil)
	Duel.Destroy(sg,REASON_EFFECT)  
	local e2=Effect.CreateEffect(e:GetHandler())  
	e2:SetType(EFFECT_TYPE_FIELD)  
	e2:SetCode(EFFECT_CANNOT_SUMMON)   
	e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET)  
	e2:SetTargetRange(1,1)  
	e2:SetTarget(c82224444.lim2)  
	e2:SetReset(RESET_PHASE+PHASE_END)  
	Duel.RegisterEffect(e2,tp)  
	local e3=Effect.CreateEffect(e:GetHandler())  
	e3:SetType(EFFECT_TYPE_FIELD)  
	e3:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON) 
	e3:SetProperty(EFFECT_FLAG_PLAYER_TARGET)  
	e3:SetTargetRange(1,1)  
	e3:SetTarget(c82224444.lim2)  
	e3:SetReset(RESET_PHASE+PHASE_END)  
	Duel.RegisterEffect(e3,tp)  
end  
function c82224444.lim2(e,c)  
	return c:IsLevel(4) and (c:IsLocation(LOCATION_HAND) or c:IsLocation(LOCATION_GRAVE))
end  
