--冬的葬礼
function c82568004.initial_effect(c)
	--Activate
	local e1=Effect.CreateEffect(c)
	e1:SetCategory(CATEGORY_SPECIAL_SUMMON)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetTarget(c82568004.target)
	e1:SetOperation(c82568004.activate)
	c:RegisterEffect(e1)
	--add code
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_SINGLE)
	e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e4:SetCode(EFFECT_ADD_CODE)
	e4:SetValue(82567785)
	c:RegisterEffect(e4)
end
function c82568004.filter(c,e,tp)
	return c:IsCode(82567852) and Duel.GetLocationCountFromEx(tp,tp,nil,c)>0 
end
function c82568004.filter2(c)
	return c:IsType(TYPE_TUNER) and c:IsLocation(LOCATION_HAND)
end
function c82568004.target(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then
		local mg1=Duel.GetRitualMaterial(tp)
		local mg=mg1:Filter(c82568004.filter2,nil)
		return Duel.IsExistingMatchingCard(aux.RitualUltimateFilter,tp,LOCATION_EXTRA,0,1,nil,c82568004.filter,e,tp,mg,nil,Card.GetOriginalLevel,"Equal")
	end
	Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,1,tp,LOCATION_EXTRA)
end
function c82568004.activate(e,tp,eg,ep,ev,re,r,rp)
	local mg=Duel.GetRitualMaterial(tp)
	Duel.Hint(HINT_SELECTMSG,tp,aux.Stringid(82568004,1))
	local tg=Duel.SelectMatchingCard(tp,aux.RitualUltimateFilter,tp,LOCATION_EXTRA,0,1,1,nil,c82568004.filter,e,tp,mg,nil,Card.GetOriginalLevel,"Equal")
	local tc=tg:GetFirst()
	if tc then
		mg=mg:Filter(Card.IsCanBeRitualMaterial,tc,tc)
		 mg=mg:Filter(c82568004.filter2,nil)
		if tc.mat_filter then
			mg=mg:Filter(tc.mat_filter,tc,tp)
		else
			mg:RemoveCard(tc)
		end
		Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_RELEASE)
		aux.GCheckAdditional=aux.RitualCheckAdditional(tc,tc:GetOriginalLevel(),"Equal")
		local mat=mg:SelectSubGroup(tp,aux.RitualCheck,false,1,tc:GetOriginalLevel(),tp,tc,tc:GetOriginalLevel(),"Equal")
		aux.GCheckAdditional=nil
		local atk=mat:GetSum(Card.GetBaseAttack)/2
		if not mat or mat:GetCount()==0 then return end
		tc:SetMaterial(mat)
		Duel.ReleaseRitualMaterial(mat)
		Duel.BreakEffect()
		Duel.SpecialSummon(tc,SUMMON_TYPE_RITUAL,tp,tp,false,true,POS_FACEUP)
		tc:CompleteProcedure()
		e:SetLabelObject(tc)
		local e1=Effect.CreateEffect(e:GetHandler())
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_SET_BASE_ATTACK)
	   e1:SetProperty(EFFECT_CANNOT_DISABLE)
		e1:SetValue(tc:GetBaseAttack()+atk)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD)
		tc:RegisterEffect(e1)
		local e2=Effect.CreateEffect(e:GetHandler())
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_CANNOT_DISABLE)
	e2:SetRange(LOCATION_MZONE)
	e2:SetCode(EFFECT_CANNOT_BE_EFFECT_TARGET)
	e2:SetReset(RESET_EVENT+RESETS_STANDARD)
	e2:SetValue(aux.tgoval)
	tc:RegisterEffect(e2)
	local e4=Effect.CreateEffect(e:GetHandler())
	e4:SetType(EFFECT_TYPE_SINGLE)
	e4:SetCode(EFFECT_INDESTRUCTABLE_EFFECT)
	e4:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_CANNOT_DISABLE)
	e4:SetReset(RESET_EVENT+RESETS_STANDARD)
	e4:SetRange(LOCATION_MZONE)
	e4:SetValue(1)
	tc:RegisterEffect(e4)
	local e7=Effect.CreateEffect(e:GetHandler())
	e7:SetCategory(CATEGORY_DAMAGE)
	e7:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_F)
	e7:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_CANNOT_DISABLE+EFFECT_FLAG_DELAY+EFFECT_FLAG_CANNOT_NEGATE)
	e7:SetReset(RESET_EVENT+RESETS_STANDARD)
	e7:SetCode(EVENT_DESTROYED)
	e7:SetCondition(c82568004.dmcon)
	e7:SetTarget(c82568004.dmtg)
	e7:SetOperation(c82568004.dmop)
	tc:RegisterEffect(e7)
	 local e5=Effect.CreateEffect(e:GetHandler())
		e5:SetType(EFFECT_TYPE_SINGLE)
		e5:SetCode(EFFECT_CANNOT_BE_FUSION_MATERIAL)
		e5:SetProperty(EFFECT_CANNOT_DISABLE)
		e5:SetValue(RESET_TURN_SET)
		e5:SetReset(RESET_EVENT+RESETS_STANDARD)
		tc:RegisterEffect(e5)
		local e6=Effect.CreateEffect(e:GetHandler())
		e6:SetType(EFFECT_TYPE_SINGLE)
		e6:SetCode(EFFECT_CANNOT_BE_LINK_MATERIAL)
		e6:SetProperty(EFFECT_CANNOT_DISABLE)
		e6:SetValue(RESET_TURN_SET)
		e6:SetReset(RESET_EVENT+RESETS_STANDARD)
		tc:RegisterEffect(e6)
		local e10=Effect.CreateEffect(e:GetHandler())
		e10:SetType(EFFECT_TYPE_SINGLE)
		e10:SetCode(EFFECT_CANNOT_BE_SYNCHRO_MATERIAL)
		e10:SetProperty(EFFECT_CANNOT_DISABLE)
		e10:SetValue(RESET_TURN_SET)
		e10:SetReset(RESET_EVENT+RESETS_STANDARD)
		tc:RegisterEffect(e10)
		 local e8=Effect.CreateEffect(e:GetHandler())
		e8:SetType(EFFECT_TYPE_SINGLE)
		e8:SetCode(EFFECT_CANNOT_BE_XYZ_MATERIAL)
		e8:SetReset(RESET_EVENT+RESETS_STANDARD)
		e8:SetProperty(EFFECT_CANNOT_DISABLE)
		e8:SetValue(RESET_TURN_SET)
		tc:RegisterEffect(e8)
		local e9=Effect.CreateEffect(e:GetHandler())
		e9:SetType(EFFECT_TYPE_SINGLE)
		e9:SetProperty(EFFECT_FLAG_SINGLE_RANGE+EFFECT_CANNOT_DISABLE)
		e9:SetReset(RESET_EVENT+RESETS_STANDARD)
		e9:SetRange(LOCATION_MZONE)
		e9:SetCode(EFFECT_UNRELEASABLE_SUM)
		e9:SetValue(1)
		tc:RegisterEffect(e9)
		local e11=e9:Clone()
		e11:SetCode(EFFECT_UNRELEASABLE_NONSUM)
		tc:RegisterEffect(e11)
	tc:RegisterFlagEffect(0,RESET_EVENT+RESETS_STANDARD,EFFECT_FLAG_CLIENT_HINT,1,0,aux.Stringid(82568004,0))
	end
end
function c82568004.efilter(e,te)
	return te:GetOwnerPlayer()~=e:GetHandlerPlayer() and te:GetOwner()~=e:GetOwner()
		and te:IsActiveType(TYPE_TRAP+TYPE_SPELL+TYPE_MONSTER)
end
function c82568004.dmcon(e,tp,eg,ep,ev,re,r,rp)
	return bit.band(r,REASON_BATTLE)~=0 
end
function c82568004.dmtg(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chkc then return true end
	if chk==0 then return true end
	Duel.SetOperationInfo(0,CATEGORY_DAMAGE,nil,nil,tp,nil)
	 Duel.SetChainLimit(aux.FALSE)
end
function c82568004.dmop(e,tp,eg,ep,ev,re,r,rp,g,tg,sg)
	local c=e:GetHandler()
	local tpp=c:GetOwner()
	if not e:GetHandler():IsRelateToEffect(e) then return end
	Duel.Damage(tpp,8000,REASON_EFFECT)
end