--武装龙·万雷 LV10000
function c88807120.initial_effect(c)
	c:EnableReviveLimit()
	--special summon condition
	local e0=Effect.CreateEffect(c)
	e0:SetType(EFFECT_TYPE_SINGLE)
	e0:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e0:SetCode(EFFECT_SPSUMMON_CONDITION)
	c:RegisterEffect(e0)
	--special summon
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_SPSUMMON_PROC)
	e1:SetProperty(EFFECT_FLAG_UNCOPYABLE)
	e1:SetRange(LOCATION_DECK)
	e1:SetCondition(c88807120.spcon)
	e1:SetOperation(c88807120.spop)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetRange(LOCATION_GRAVE)
	c:RegisterEffect(e2)
	--atk up
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e3:SetRange(LOCATION_MZONE)
	e3:SetCode(EFFECT_UPDATE_ATTACK)
	e3:SetValue(10000)
	e3:SetCondition(c88807120.atkcon)
	c:RegisterEffect(e3)
	local e4=e3:Clone()
	e4:SetCode(EFFECT_UPDATE_DEFENSE)
	c:RegisterEffect(e4)
	--Activate
	local e5=Effect.CreateEffect(c)
	e5:SetCategory(CATEGORY_DRAW)
	e5:SetType(EFFECT_TYPE_IGNITION)
	e5:SetRange(LOCATION_MZONE)
	e5:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e5:SetCountLimit(1,88807120)
	e5:SetTarget(c88807120.target)
	e5:SetOperation(c88807120.activate)
	c:RegisterEffect(e5)
	--cannot target
	local e6=Effect.CreateEffect(c)
	e6:SetType(EFFECT_TYPE_SINGLE)
	e6:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e6:SetRange(LOCATION_MZONE)
	e6:SetCode(EFFECT_CANNOT_BE_EFFECT_TARGET)
	e6:SetValue(aux.tgoval)
	c:RegisterEffect(e6)
	--indes
	local e7=Effect.CreateEffect(c)
	e7:SetType(EFFECT_TYPE_SINGLE)
	e7:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e7:SetRange(LOCATION_MZONE)
	e7:SetCode(EFFECT_CANNOT_CHANGE_CONTROL)
	e7:SetValue(1)
	c:RegisterEffect(e7)
	--immune
	local e12=Effect.CreateEffect(c)
	e12:SetType(EFFECT_TYPE_SINGLE)
	e12:SetCode(EFFECT_INDESTRUCTABLE_EFFECT)
	e12:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e12:SetRange(LOCATION_MZONE)
	e12:SetValue(1)
	c:RegisterEffect(e12)
end
function c88807120.filter(c)
	return c:IsFaceup() and c:IsSetCard(0x111) and c:IsType(TYPE_MONSTER)
end
function c88807120.target(e,tp,eg,ep,ev,re,r,rp,chk)
	local g=Duel.GetMatchingGroup(c88807120.filter,tp,LOCATION_REMOVED,0,nil)
	local ct=g:GetClassCount(Card.GetCode)
	if chk==0 then return ct>0 and Duel.IsPlayerCanDraw(tp,ct) end
	Duel.SetTargetPlayer(tp)
	Duel.SetTargetParam(ct)
	Duel.SetOperationInfo(0,CATEGORY_DRAW,nil,0,tp,ct)
	Duel.SetOperationInfo(0,CATEGORY_TODECK,nil,0,tp,2)
end
function c88807120.activate(e,tp,eg,ep,ev,re,r,rp)
	local p=Duel.GetChainInfo(0,CHAININFO_TARGET_PLAYER)
	local g=Duel.GetMatchingGroup(c88807120.filter,tp,LOCATION_REMOVED,0,nil)
	local ct=g:GetClassCount(Card.GetCode)
	Duel.Draw(p,ct,REASON_EFFECT)
		local g=Duel.GetMatchingGroup(Card.IsAbleToDeck,p,LOCATION_HAND,0,nil)
		if g:GetCount()<2 then return end
		Duel.ShuffleHand(p)
		Duel.BreakEffect()
		Duel.Hint(HINT_SELECTMSG,p,HINTMSG_TODECK)
		local sg=g:Select(p,2,2,nil)
		aux.PlaceCardsOnDeckBottom(p,sg)
	end
function c88807120.spfilter(c,att)
	return c:IsCode(att) and c:IsAbleToRemoveAsCost()
end
function c88807120.spcon(e,c)
	if c==nil then return true end
	local tp=c:GetControler() 
	return Duel.GetLocationCount(tp,LOCATION_MZONE)>0
		and Duel.IsExistingMatchingCard(c88807120.spfilter,tp,LOCATION_GRAVE+LOCATION_MZONE,0,1,nil,980973)
		and Duel.IsExistingMatchingCard(c88807120.spfilter,tp,LOCATION_GRAVE+LOCATION_MZONE,0,1,nil,46384672)
		and Duel.IsExistingMatchingCard(c88807120.spfilter,tp,LOCATION_GRAVE+LOCATION_MZONE,0,1,nil,73879377)
		and Duel.IsExistingMatchingCard(c88807120.spfilter,tp,LOCATION_GRAVE+LOCATION_MZONE,0,1,nil,59464593)
end
function c88807120.spop(e,tp,eg,ep,ev,re,r,rp,c)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_REMOVE)
	local g1=Duel.SelectMatchingCard(tp,c88807120.spfilter,tp,LOCATION_GRAVE+LOCATION_MZONE,0,1,1,nil,980973)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_REMOVE)
	local g2=Duel.SelectMatchingCard(tp,c88807120.spfilter,tp,LOCATION_GRAVE+LOCATION_MZONE,0,1,1,nil,46384672)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_REMOVE)
	local g3=Duel.SelectMatchingCard(tp,c88807120.spfilter,tp,LOCATION_GRAVE+LOCATION_MZONE,0,1,1,nil,73879377)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_REMOVE)
	local g4=Duel.SelectMatchingCard(tp,c88807120.spfilter,tp,LOCATION_GRAVE+LOCATION_MZONE,0,1,1,nil,59464593)
	g1:Merge(g2)
	g1:Merge(g3)
	g1:Merge(g4)
	Duel.Remove(g1,POS_FACEUP,REASON_COST)
end
function c88807120.atkfilter(c)
	return c:IsFaceup() and c:IsSetCard(0x111) 
end
function c88807120.atkcon(e)
	local tp=e:GetHandlerPlayer()
	local g=Duel.GetMatchingGroup(c88807120.atkfilter,tp,LOCATION_REMOVED,0,nil)
	return g:GetClassCount(Card.GetCode)>=4
end
