--影假身骑士
local m=89387021
local cm=_G["c"..m]
function cm.initial_effect(c)
    local e1=Effect.CreateEffect(c)
    e1:SetType(EFFECT_TYPE_SINGLE)
    e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
    e1:SetCode(EFFECT_SPSUMMON_CONDITION)
    c:RegisterEffect(e1)
    local e2=Effect.CreateEffect(c)
    e2:SetType(EFFECT_TYPE_SINGLE)
    e2:SetCode(EFFECT_TRIBUTE_LIMIT)
    e2:SetValue(cm.tlimit)
    c:RegisterEffect(e2)
    local e3=Effect.CreateEffect(c)
    e3:SetDescription(aux.Stringid(m,0))
    e3:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
    e3:SetType(EFFECT_TYPE_SINGLE)
    e3:SetCode(EFFECT_LIMIT_SUMMON_PROC)
    e3:SetCondition(cm.ttcon)
    e3:SetOperation(cm.ttop)
    e3:SetValue(SUMMON_TYPE_ADVANCE)
    c:RegisterEffect(e3)
    local e0=Effect.CreateEffect(c)
    e0:SetDescription(aux.Stringid(m,1))
    e0:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_SPSUM_PARAM)
    e0:SetType(EFFECT_TYPE_SINGLE)
    e0:SetCode(EFFECT_LIMIT_SUMMON_PROC)
    e0:SetTargetRange(POS_FACEUP_ATTACK,0)
    e0:SetCondition(cm.ttcon2)
    e0:SetOperation(cm.ttop2)
    e0:SetValue(SUMMON_TYPE_ADVANCE)
    c:RegisterEffect(e0)
    local e4=Effect.CreateEffect(c)
    e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
    e4:SetType(EFFECT_TYPE_SINGLE)
    e4:SetCode(EFFECT_LIMIT_SET_PROC)
    e4:SetCondition(cm.setcon)
    c:RegisterEffect(e4)
    local e6=Effect.CreateEffect(c)
    e6:SetType(EFFECT_TYPE_SINGLE)
    e6:SetCode(EFFECT_MATERIAL_CHECK)
    e6:SetValue(cm.valcheck)
    c:RegisterEffect(e6)
    local e5=Effect.CreateEffect(c)
    e5:SetType(EFFECT_TYPE_SINGLE)
    e5:SetCode(EFFECT_SUMMON_COST)
    e5:SetOperation(cm.facechk)
    e5:SetLabelObject(e6)
    c:RegisterEffect(e5)
    local e7=Effect.CreateEffect(c)
    e7:SetCategory(CATEGORY_DRAW)
    e7:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_F)
    e7:SetCode(EVENT_SUMMON_SUCCESS)
    e7:SetCondition(cm.drcon)
    e7:SetTarget(cm.drtg)
    e7:SetOperation(cm.drop)
    c:RegisterEffect(e7)
end
function cm.tlimit(e,c)
    return c:IsFacedown()
end
function cm.ttcon(e,c,minc)
    if c==nil then return true end
    local tp=c:GetControler()
    local mg=Duel.GetMatchingGroup(Card.IsFaceup,tp,LOCATION_MZONE,0,nil)
    return minc<=1 and Duel.CheckTribute(c,1,1,mg)
end
function cm.ttop(e,tp,eg,ep,ev,re,r,rp,c)
    local mg=Duel.GetMatchingGroup(Card.IsFaceup,tp,LOCATION_MZONE,0,nil)
    local sg=Duel.SelectTribute(tp,c,1,1,mg)
    c:SetMaterial(sg)
    Duel.Release(sg,REASON_SUMMON+REASON_MATERIAL)
end
function cm.ttcon2(e,c,minc)
    if c==nil then return true end
    local tp=c:GetControler()
    local mg=Duel.GetMatchingGroup(Card.IsFaceup,tp,0,LOCATION_MZONE,nil)
    return minc<=1 and Duel.CheckTribute(c,1,1,mg,1-tp)
end
function cm.ttop2(e,tp,eg,ep,ev,re,r,rp,c)
    local mg=Duel.GetMatchingGroup(Card.IsFaceup,tp,0,LOCATION_MZONE,nil)
    local sg=Duel.SelectTribute(tp,c,1,1,mg,1-tp)
    c:SetMaterial(sg)
    Duel.Release(sg,REASON_SUMMON+REASON_MATERIAL)
end
function cm.setcon(e,c,minc)
    if not c then return true end
    return false
end
function cm.valcheck(e,c)
    local tc=c:GetMaterial():GetFirst()
    if e:GetLabel()==1 then
        e:SetLabel(0)
        local e1=Effect.CreateEffect(c)
        e1:SetType(EFFECT_TYPE_SINGLE)
        e1:SetCode(EFFECT_UPDATE_ATTACK)
        e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
        e1:SetRange(LOCATION_MZONE)
        e1:SetValue(tc:GetAttack())
        e1:SetReset(RESET_EVENT+0xff0000)
        c:RegisterEffect(e1)
        local e2=e1:Clone()
        e2:SetCode(EFFECT_UPDATE_DEFENSE)
        e2:SetValue(tc:GetDefense())
        c:RegisterEffect(e2)
        local e3=e1:Clone()
        e3:SetCode(EFFECT_ADD_ATTRIBUTE)
        e3:SetValue(tc:GetAttribute())
        c:RegisterEffect(e3)
        local e4=e1:Clone()
        e4:SetCode(EFFECT_ADD_RACE)
        e4:SetValue(tc:GetRace())
        c:RegisterEffect(e4)
        local e5=e1:Clone()
        e5:SetCode(EFFECT_ADD_CODE)
        e5:SetValue(tc:GetOriginalCode())
        c:RegisterEffect(e5)
        c:CopyEffect(tc:GetOriginalCode(),RESET_EVENT+0xff0000)
    end
end
function cm.facechk(e,tp,eg,ep,ev,re,r,rp)
    e:GetLabelObject():SetLabel(1)
end
function cm.drcon(e,tp,eg,ep,ev,re,r,rp)
    return e:GetHandler():GetMaterial():GetFirst():GetOwner()~=tp
end
function cm.drtg(e,tp,eg,ep,ev,re,r,rp,chk)
    if chk==0 then return true end
    Duel.SetTargetPlayer(1-tp)
    Duel.SetTargetParam(1)
    Duel.SetOperationInfo(0,CATEGORY_DRAW,nil,0,1-tp,1)
end
function cm.drop(e,tp,eg,ep,ev,re,r,rp)
    local p,d=Duel.GetChainInfo(0,CHAININFO_TARGET_PLAYER,CHAININFO_TARGET_PARAM)
    Duel.Draw(p,d,REASON_EFFECT)
end
