--真神招来
local m=91020023
local cm=c91020023
function c91020023.initial_effect(c)
--to hand
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	c:RegisterEffect(e1)
	--Atk&Def
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD)
	e2:SetCode(EFFECT_UPDATE_ATTACK)
	e2:SetRange(LOCATION_FZONE)
	e2:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e2:SetTarget(aux.TargetBoolFunction(Card.IsSetCard,0x9d1))
	e2:SetValue(500)
	c:RegisterEffect(e2)
	local e3=e2:Clone()
	e3:SetCode(EFFECT_UPDATE_DEFENSE)
	c:RegisterEffect(e3)
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O)
	e4:SetProperty(EFFECT_FLAG_DELAY)
	e4:SetRange(LOCATION_FZONE)
	e4:SetCode(EVENT_RELEASE)
	e4:SetCountLimit(1,m)
	e4:SetCondition(cm.con2)
	e4:SetTarget(cm.tg2)
	e4:SetOperation(cm.op2)
	c:RegisterEffect(e4)
	  local e3=Effect.CreateEffect(c)
	 e3:SetType(EFFECT_TYPE_FIELD)
	 e3:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	 e3:SetCode(EFFECT_CANNOT_REMOVE)
	 e3:SetTargetRange(0,1)
	 e3:SetRange(LOCATION_FZONE)
	 e3:SetTarget(cm.efilter)
	  local e5=Effect.CreateEffect(c)
	 e5:SetType(EFFECT_TYPE_FIELD)
	 e5:SetCode(EFFECT_CANNOT_INACTIVATE)
	 e5:SetRange(LOCATION_FZONE)
	 e5:SetValue(cm.effectfilter)
   local e6=Effect.CreateEffect(c)
	 e6:SetType(EFFECT_TYPE_FIELD)
	 e6:SetCode(EFFECT_CANNOT_DISEFFECT)
	 e6:SetRange(LOCATION_FZONE)
	 e6:SetValue(cm.effectfilter)
end
function cm.fit2(c)
	return  c:IsSetCard(0x9d1) 
end
function cm.con2(e,tp,eg,ep,ev,re,r,rp)
	return  eg:IsExists(cm.fit2,1,nil)
end
function cm.tg2(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetLocationCount(tp,LOCATION_MZONE)>0 end	
	Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,nil,0,LOCATION_GRAVE)
	Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,nil,0,LOCATION_REMOVED)
end
function cm.op2(e,tp,eg,ep,ev,re,r,rp)
	local g=Duel.SelectMatchingCard(tp,cm.fit2,tp,LOCATION_GRAVE+LOCATION_REMOVED,0,1,1,nil)
		Duel.SpecialSummon(g,0,tp,tp,false,false,POS_FACEUP)	
end
function cm.efilter(e,c,rp,r,re)
	local tp=e:GetHandlerPlayer()
	return c:IsFaceup() and c:IsControler(tp) and c:IsLocation(LOCATION_GRAVE) and re and r&REASON_EFFECT>0 and rp==1-tp and c:IsSetCard(0x9d1)
end
function cm.effectfilter(e,ct)
	local p=e:GetHandler():GetControler()
	local te,tp,loc=Duel.GetChainInfo(ct,CHAININFO_TRIGGERING_EFFECT,CHAININFO_TRIGGERING_PLAYER,CHAININFO_TRIGGERING_LOCATION)
	return p==tp and bit.band(loc,LOCATION_GRAVE)~=0 and te:GetHandler():IsSetCard(0x9d1)
end
